/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/DonkeyKong.glb --types --keepnames --transform
*/

import * as THREE from 'three'
import React from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Joint_0_Object_0: THREE.SkinnedMesh
        Joint_0_Object_1: THREE.SkinnedMesh
        Joint_0_Object_10: THREE.SkinnedMesh
        Joint_0_Object_11: THREE.SkinnedMesh
        Joint_0_Object_12: THREE.SkinnedMesh
        Joint_0_Object_13: THREE.SkinnedMesh
        Joint_0_Object_14: THREE.SkinnedMesh
        Joint_0_Object_15: THREE.SkinnedMesh
        Joint_0_Object_16: THREE.SkinnedMesh
        Joint_0_Object_17: THREE.SkinnedMesh
        Joint_0_Object_18: THREE.SkinnedMesh
        Joint_0_Object_19: THREE.SkinnedMesh
        Joint_0_Object_2: THREE.SkinnedMesh
        Joint_0_Object_3: THREE.SkinnedMesh
        Joint_0_Object_34: THREE.SkinnedMesh
        Joint_0_Object_4: THREE.SkinnedMesh
        Joint_0_Object_5: THREE.SkinnedMesh
        Joint_0_Object_7: THREE.SkinnedMesh
        Joint_0_Object_8: THREE.SkinnedMesh
        Joint_0_Object_9: THREE.SkinnedMesh
        Joint_48_Object_1_SINGLE: THREE.SkinnedMesh
        JOBJ_0: THREE.Bone
    }
    materials: {
        Joint_0_Object_0_Material_0: THREE.MeshStandardMaterial
        Joint_0_Object_1_Material_1: THREE.MeshStandardMaterial
        Joint_0_Object_10_Material_10: THREE.MeshStandardMaterial
        Joint_0_Object_11_Material_11: THREE.MeshStandardMaterial
        Joint_0_Object_12_Material_12: THREE.MeshStandardMaterial
        Joint_0_Object_13_Material_13: THREE.MeshStandardMaterial
        Joint_0_Object_14_Material_14: THREE.MeshStandardMaterial
        Joint_0_Object_15_Material_15: THREE.MeshStandardMaterial
        Joint_0_Object_16_Material_16: THREE.MeshStandardMaterial
        Joint_0_Object_17_Material_17: THREE.MeshStandardMaterial
        Joint_0_Object_18_Material_18: THREE.MeshStandardMaterial
        Joint_0_Object_19_Material_19: THREE.MeshStandardMaterial
        Joint_0_Object_2_Material_2: THREE.MeshStandardMaterial
        Joint_0_Object_3_Material_3: THREE.MeshStandardMaterial
        Joint_0_Object_34_Material_34: THREE.MeshStandardMaterial
        Joint_0_Object_4_Material_4: THREE.MeshStandardMaterial
        Joint_0_Object_5_Material_5: THREE.MeshStandardMaterial
        Joint_0_Object_7_Material_7: THREE.MeshStandardMaterial
        Joint_0_Object_8_Material_8: THREE.MeshStandardMaterial
        Joint_0_Object_9_Material_9: THREE.MeshStandardMaterial
        Joint_48_Object_1_Material_1: THREE.MeshStandardMaterial
    }
}

export default function DonkeyKong(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/DonkeyKong-transformed.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
                <primitive object={nodes.JOBJ_0}/>
                <skinnedMesh name="Joint_0_Object_0" geometry={nodes.Joint_0_Object_0.geometry}
                             material={materials.Joint_0_Object_0_Material_0}
                             skeleton={nodes.Joint_0_Object_0.skeleton}/>
                <skinnedMesh name="Joint_0_Object_1" geometry={nodes.Joint_0_Object_1.geometry}
                             material={materials.Joint_0_Object_1_Material_1}
                             skeleton={nodes.Joint_0_Object_1.skeleton}/>
                <skinnedMesh name="Joint_0_Object_10" geometry={nodes.Joint_0_Object_10.geometry}
                             material={materials.Joint_0_Object_10_Material_10}
                             skeleton={nodes.Joint_0_Object_10.skeleton}/>
                <skinnedMesh name="Joint_0_Object_11" geometry={nodes.Joint_0_Object_11.geometry}
                             material={materials.Joint_0_Object_11_Material_11}
                             skeleton={nodes.Joint_0_Object_11.skeleton}/>
                <skinnedMesh name="Joint_0_Object_12" geometry={nodes.Joint_0_Object_12.geometry}
                             material={materials.Joint_0_Object_12_Material_12}
                             skeleton={nodes.Joint_0_Object_12.skeleton}/>
                <skinnedMesh name="Joint_0_Object_13" geometry={nodes.Joint_0_Object_13.geometry}
                             material={materials.Joint_0_Object_13_Material_13}
                             skeleton={nodes.Joint_0_Object_13.skeleton}/>
                <skinnedMesh name="Joint_0_Object_14" geometry={nodes.Joint_0_Object_14.geometry}
                             material={materials.Joint_0_Object_14_Material_14}
                             skeleton={nodes.Joint_0_Object_14.skeleton}/>
                <skinnedMesh name="Joint_0_Object_15" geometry={nodes.Joint_0_Object_15.geometry}
                             material={materials.Joint_0_Object_15_Material_15}
                             skeleton={nodes.Joint_0_Object_15.skeleton}/>
                <skinnedMesh name="Joint_0_Object_16" geometry={nodes.Joint_0_Object_16.geometry}
                             material={materials.Joint_0_Object_16_Material_16}
                             skeleton={nodes.Joint_0_Object_16.skeleton}/>
                <skinnedMesh name="Joint_0_Object_17" geometry={nodes.Joint_0_Object_17.geometry}
                             material={materials.Joint_0_Object_17_Material_17}
                             skeleton={nodes.Joint_0_Object_17.skeleton}/>
                <skinnedMesh name="Joint_0_Object_18" geometry={nodes.Joint_0_Object_18.geometry}
                             material={materials.Joint_0_Object_18_Material_18}
                             skeleton={nodes.Joint_0_Object_18.skeleton}/>
                <skinnedMesh name="Joint_0_Object_19" geometry={nodes.Joint_0_Object_19.geometry}
                             material={materials.Joint_0_Object_19_Material_19}
                             skeleton={nodes.Joint_0_Object_19.skeleton}/>
                <skinnedMesh name="Joint_0_Object_2" geometry={nodes.Joint_0_Object_2.geometry}
                             material={materials.Joint_0_Object_2_Material_2}
                             skeleton={nodes.Joint_0_Object_2.skeleton}/>
                <skinnedMesh name="Joint_0_Object_3" geometry={nodes.Joint_0_Object_3.geometry}
                             material={materials.Joint_0_Object_3_Material_3}
                             skeleton={nodes.Joint_0_Object_3.skeleton}/>
                <skinnedMesh name="Joint_0_Object_34" geometry={nodes.Joint_0_Object_34.geometry}
                             material={materials.Joint_0_Object_34_Material_34}
                             skeleton={nodes.Joint_0_Object_34.skeleton}/>
                <skinnedMesh name="Joint_0_Object_4" geometry={nodes.Joint_0_Object_4.geometry}
                             material={materials.Joint_0_Object_4_Material_4}
                             skeleton={nodes.Joint_0_Object_4.skeleton}/>
                <skinnedMesh name="Joint_0_Object_5" geometry={nodes.Joint_0_Object_5.geometry}
                             material={materials.Joint_0_Object_5_Material_5}
                             skeleton={nodes.Joint_0_Object_5.skeleton}/>
                <skinnedMesh name="Joint_0_Object_7" geometry={nodes.Joint_0_Object_7.geometry}
                             material={materials.Joint_0_Object_7_Material_7}
                             skeleton={nodes.Joint_0_Object_7.skeleton}/>
                <skinnedMesh name="Joint_0_Object_8" geometry={nodes.Joint_0_Object_8.geometry}
                             material={materials.Joint_0_Object_8_Material_8}
                             skeleton={nodes.Joint_0_Object_8.skeleton}/>
                <skinnedMesh name="Joint_0_Object_9" geometry={nodes.Joint_0_Object_9.geometry}
                             material={materials.Joint_0_Object_9_Material_9}
                             skeleton={nodes.Joint_0_Object_9.skeleton}/>
                <skinnedMesh name="Joint_48_Object_1_SINGLE" geometry={nodes.Joint_48_Object_1_SINGLE.geometry}
                             material={materials.Joint_48_Object_1_Material_1}
                             skeleton={nodes.Joint_48_Object_1_SINGLE.skeleton}/>
            </group>
        </group>
    )
}

useGLTF.preload('DonkeyKong-transformed.glb')
