/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Yoshi.glb --types --keepnames --transform
*/

import * as THREE from 'three'
import React from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        DrawCall_31: THREE.Mesh
        DrawCall_33: THREE.Mesh
        DrawCall_35: THREE.Mesh
        DrawCall_38: THREE.Mesh
        DrawCall_43: THREE.Mesh
        DrawCall_50: THREE.Mesh
        DrawCall_51: THREE.Mesh
    }
    materials: {
        yoshi_back: THREE.MeshStandardMaterial
        yoshi_scale: THREE.MeshStandardMaterial
        yoshi_skin: THREE.MeshStandardMaterial
        yoshi_cheeks: THREE.MeshStandardMaterial
        yoshi_shoe: THREE.MeshStandardMaterial
        yoshi_eye: THREE.MeshStandardMaterial
    }
}

export default function Yoshi(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/Yoshi-transformed.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh name="DrawCall_31" geometry={nodes.DrawCall_31.geometry} material={materials.yoshi_back}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh name="DrawCall_33" geometry={nodes.DrawCall_33.geometry} material={materials.yoshi_scale}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh name="DrawCall_35" geometry={nodes.DrawCall_35.geometry} material={materials.yoshi_skin}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh name="DrawCall_38" geometry={nodes.DrawCall_38.geometry} material={materials.yoshi_cheeks}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh name="DrawCall_43" geometry={nodes.DrawCall_43.geometry} material={materials.yoshi_shoe}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh name="DrawCall_50" geometry={nodes.DrawCall_50.geometry} material={materials.yoshi_eye}
                  rotation={[Math.PI / 2, 0, 0]}/>
            <mesh name="DrawCall_51" geometry={nodes.DrawCall_51.geometry} material={materials.yoshi_eye}
                  rotation={[Math.PI / 2, 0, 0]}/>
        </group>
    )
}

useGLTF.preload('/Yoshi-transformed.glb')
