/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Fountain_render.glb --types --keepnames --transform
*/

import * as THREE from 'three'
import {AnimationClip} from 'three'
import React, {useRef} from 'react'
import {useAnimations, useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'

type ActionName = 'new_anim.004' | 'new_anim'

interface GLTFAction extends AnimationClip {
    name: ActionName;
}

type GLTFResult = GLTF & {
    nodes: {
        Joint_10_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_20_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_23_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_24_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_25_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_26_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_27_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_28_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_29_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_30_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_31_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_32_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_33_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_34_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_35_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_37_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_38_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_38_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_38_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_38_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_39_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_39_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_39_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_39_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_40_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_40_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_40_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_40_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_41_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_41_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_41_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_41_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_42_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_42_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_42_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_42_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_43_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_43_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_43_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_43_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_44_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_44_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_44_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_44_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_45_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_45_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_45_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_45_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_46_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_46_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_47_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_48_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_48_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_49_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_5_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_8_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_9_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_10_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_11_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_12_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_15_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_16_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_17_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_19_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_1_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_1_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_22_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_23_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_24_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_25_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_26_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_27_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_29_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_2_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_30_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_31_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_32_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_33_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_34_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_35_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_35_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_35_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_35_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_36_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_17_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_36_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_38_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_39_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_3_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_3_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_40_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_41_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_42_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_43_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_44_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_46_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_47_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_48_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_49_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_50_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_51_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_52_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_53_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_54_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_17_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_18_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_19_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_8_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_9_Object_0_SINGLE001: THREE.SkinnedMesh
        water_top_1: THREE.Mesh
        water_top_2: THREE.Mesh
        water_top_3: THREE.Mesh
        water_top_4: THREE.Mesh
        water_top_5: THREE.Mesh
        water_top_6: THREE.Mesh
        water_top_7: THREE.Mesh
        Joint_0_Object_0002: THREE.SkinnedMesh
        water_bot_1: THREE.Mesh
        water_bot_2: THREE.Mesh
        water_top_8: THREE.Mesh
        water_top_9: THREE.Mesh
        water_top_10: THREE.Mesh
        water_top_11: THREE.Mesh
        water_top_12: THREE.Mesh
        water_top_13: THREE.Mesh
        water_top_14: THREE.Mesh
        Joint_0_Object_0001: THREE.SkinnedMesh
        water_bot_3: THREE.Mesh
        water_bot_4: THREE.Mesh
        Sphere_instance: THREE.Mesh
        water_top: THREE.Mesh
        water_bot: THREE.Mesh
        Cube: THREE.Mesh
        JOBJ_0: THREE.Bone
        JOBJ_0_1: THREE.Bone
        JOBJ_0_2: THREE.Bone
        JOBJ_0_3: THREE.Bone
    }
    materials: {
        Joint_10_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_11_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_12_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_14_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_16_Object_0_Material_0: THREE.MeshStandardMaterial
        Joint_18_Object_0_Material_0: THREE.MeshStandardMaterial
        Joint_1_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_21_Object_0_Material_0: THREE.MeshStandardMaterial
        Joint_38_Object_0_Material_0: THREE.MeshStandardMaterial
        Joint_3_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_46_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_46_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_4_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_8_Object_0_Material_0: THREE.MeshBasicMaterial
        ['Joint_10_Object_0_Material_0.001']: THREE.MeshStandardMaterial
        ['Joint_14_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        ['Joint_1_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        Joint_1_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_1_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_2_Object_2_Material_2: THREE.MeshBasicMaterial
        ['Joint_32_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        ['Joint_35_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        Joint_36_Object_14_Material_14: THREE.MeshBasicMaterial
        Joint_36_Object_15_Material_15: THREE.MeshBasicMaterial
        ['Joint_44_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        Joint_7_Object_11_Material_11: THREE.MeshBasicMaterial
        Joint_7_Object_12_Material_12: THREE.MeshBasicMaterial
        Joint_7_Object_1_Material_1: THREE.MeshBasicMaterial
        ['Joint_9_Object_0_Material_0.001']: THREE.MeshStandardMaterial
        particle_top: THREE.MeshBasicMaterial
        ['Joint_0_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        Material: THREE.MeshStandardMaterial
        ['Material.001']: THREE.MeshStandardMaterial
    },
    animations: GLTFAction[]
}

export default function FountainOfDreams(props: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>(null)
    const {
        nodes,
        materials,
        animations
    } = useGLTF(`${import.meta.env.BASE_URL}/Fountain_render-transformed.glb`) as unknown as GLTFResult
    const {actions} = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="model">
                <group name="model_skeleton">
                    <primitive object={nodes.JOBJ_0}/>
                    <skinnedMesh name="Joint_10_Object_0_SINGLE" geometry={nodes.Joint_10_Object_0_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_10_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_0_SINGLE" geometry={nodes.Joint_11_Object_0_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_11_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_0_SINGLE" geometry={nodes.Joint_12_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_12_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_13_Object_0_SINGLE" geometry={nodes.Joint_13_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_13_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_14_Object_0_SINGLE" geometry={nodes.Joint_14_Object_0_SINGLE.geometry}
                                 material={materials.Joint_14_Object_0_Material_0}
                                 skeleton={nodes.Joint_14_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_15_Object_0_SINGLE" geometry={nodes.Joint_15_Object_0_SINGLE.geometry}
                                 material={materials.Joint_14_Object_0_Material_0}
                                 skeleton={nodes.Joint_15_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_0_SINGLE" geometry={nodes.Joint_16_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_1_SINGLE" geometry={nodes.Joint_16_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_2_SINGLE" geometry={nodes.Joint_16_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_3_SINGLE" geometry={nodes.Joint_16_Object_3_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_0_SINGLE" geometry={nodes.Joint_18_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_19_Object_0_SINGLE" geometry={nodes.Joint_19_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_19_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_0_SINGLE" geometry={nodes.Joint_1_Object_0_SINGLE.geometry}
                                 material={materials.Joint_1_Object_0_Material_0}
                                 skeleton={nodes.Joint_1_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_20_Object_0_SINGLE" geometry={nodes.Joint_20_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_20_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_21_Object_0_SINGLE" geometry={nodes.Joint_21_Object_0_SINGLE.geometry}
                                 material={materials.Joint_21_Object_0_Material_0}
                                 skeleton={nodes.Joint_21_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_22_Object_0_SINGLE" geometry={nodes.Joint_22_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_22_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_23_Object_0_SINGLE" geometry={nodes.Joint_23_Object_0_SINGLE.geometry}
                                 material={materials.Joint_21_Object_0_Material_0}
                                 skeleton={nodes.Joint_23_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_24_Object_0_SINGLE" geometry={nodes.Joint_24_Object_0_SINGLE.geometry}
                                 material={materials.Joint_21_Object_0_Material_0}
                                 skeleton={nodes.Joint_24_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_25_Object_0_SINGLE" geometry={nodes.Joint_25_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_25_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_26_Object_0_SINGLE" geometry={nodes.Joint_26_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_26_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_27_Object_0_SINGLE" geometry={nodes.Joint_27_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_27_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_28_Object_0_SINGLE" geometry={nodes.Joint_28_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_28_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_29_Object_0_SINGLE" geometry={nodes.Joint_29_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_29_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_30_Object_0_SINGLE" geometry={nodes.Joint_30_Object_0_SINGLE.geometry}
                                 material={materials.Joint_21_Object_0_Material_0}
                                 skeleton={nodes.Joint_30_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_31_Object_0_SINGLE" geometry={nodes.Joint_31_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_31_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_32_Object_0_SINGLE" geometry={nodes.Joint_32_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_32_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_33_Object_0_SINGLE" geometry={nodes.Joint_33_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_33_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_34_Object_0_SINGLE" geometry={nodes.Joint_34_Object_0_SINGLE.geometry}
                                 material={materials.Joint_21_Object_0_Material_0}
                                 skeleton={nodes.Joint_34_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_35_Object_0_SINGLE" geometry={nodes.Joint_35_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_35_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_0_SINGLE" geometry={nodes.Joint_36_Object_0_SINGLE.geometry}
                                 material={materials.Joint_18_Object_0_Material_0}
                                 skeleton={nodes.Joint_36_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_37_Object_0_SINGLE" geometry={nodes.Joint_37_Object_0_SINGLE.geometry}
                                 material={materials.Joint_21_Object_0_Material_0}
                                 skeleton={nodes.Joint_37_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_38_Object_0_SINGLE" geometry={nodes.Joint_38_Object_0_SINGLE.geometry}
                                 material={materials.Joint_38_Object_0_Material_0}
                                 skeleton={nodes.Joint_38_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_38_Object_1_SINGLE" geometry={nodes.Joint_38_Object_1_SINGLE.geometry}
                                 material={materials.Joint_38_Object_0_Material_0}
                                 skeleton={nodes.Joint_38_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_38_Object_2_SINGLE" geometry={nodes.Joint_38_Object_2_SINGLE.geometry}
                                 material={materials.Joint_38_Object_0_Material_0}
                                 skeleton={nodes.Joint_38_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_38_Object_3_SINGLE" geometry={nodes.Joint_38_Object_3_SINGLE.geometry}
                                 material={materials.Joint_38_Object_0_Material_0}
                                 skeleton={nodes.Joint_38_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_39_Object_0_SINGLE" geometry={nodes.Joint_39_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_39_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_39_Object_1_SINGLE" geometry={nodes.Joint_39_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_39_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_39_Object_2_SINGLE" geometry={nodes.Joint_39_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_39_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_39_Object_3_SINGLE" geometry={nodes.Joint_39_Object_3_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_39_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_0_SINGLE" geometry={nodes.Joint_3_Object_0_SINGLE.geometry}
                                 material={materials.Joint_3_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_40_Object_0_SINGLE" geometry={nodes.Joint_40_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_40_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_40_Object_1_SINGLE" geometry={nodes.Joint_40_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_40_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_40_Object_2_SINGLE" geometry={nodes.Joint_40_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_40_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_40_Object_3_SINGLE" geometry={nodes.Joint_40_Object_3_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_40_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_41_Object_0_SINGLE" geometry={nodes.Joint_41_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_41_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_41_Object_1_SINGLE" geometry={nodes.Joint_41_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_41_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_41_Object_2_SINGLE" geometry={nodes.Joint_41_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_41_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_41_Object_3_SINGLE" geometry={nodes.Joint_41_Object_3_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_41_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_42_Object_0_SINGLE" geometry={nodes.Joint_42_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_42_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_42_Object_1_SINGLE" geometry={nodes.Joint_42_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_42_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_42_Object_2_SINGLE" geometry={nodes.Joint_42_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_42_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_42_Object_3_SINGLE" geometry={nodes.Joint_42_Object_3_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_42_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_43_Object_0_SINGLE" geometry={nodes.Joint_43_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_43_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_43_Object_1_SINGLE" geometry={nodes.Joint_43_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_43_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_43_Object_2_SINGLE" geometry={nodes.Joint_43_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_43_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_43_Object_3_SINGLE" geometry={nodes.Joint_43_Object_3_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_43_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_44_Object_0_SINGLE" geometry={nodes.Joint_44_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_44_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_44_Object_1_SINGLE" geometry={nodes.Joint_44_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_44_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_44_Object_2_SINGLE" geometry={nodes.Joint_44_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_44_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_44_Object_3_SINGLE" geometry={nodes.Joint_44_Object_3_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_44_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_45_Object_0_SINGLE" geometry={nodes.Joint_45_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_45_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_45_Object_1_SINGLE" geometry={nodes.Joint_45_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_45_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_45_Object_2_SINGLE" geometry={nodes.Joint_45_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_45_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_45_Object_3_SINGLE" geometry={nodes.Joint_45_Object_3_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_45_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_46_Object_0_SINGLE" geometry={nodes.Joint_46_Object_0_SINGLE.geometry}
                                 material={materials.Joint_46_Object_0_Material_0}
                                 skeleton={nodes.Joint_46_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_46_Object_1_SINGLE" geometry={nodes.Joint_46_Object_1_SINGLE.geometry}
                                 material={materials.Joint_46_Object_1_Material_1}
                                 skeleton={nodes.Joint_46_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_47_Object_0_SINGLE" geometry={nodes.Joint_47_Object_0_SINGLE.geometry}
                                 material={materials.Joint_46_Object_1_Material_1}
                                 skeleton={nodes.Joint_47_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_48_Object_0_SINGLE" geometry={nodes.Joint_48_Object_0_SINGLE.geometry}
                                 material={materials.Joint_46_Object_0_Material_0}
                                 skeleton={nodes.Joint_48_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_48_Object_1_SINGLE" geometry={nodes.Joint_48_Object_1_SINGLE.geometry}
                                 material={materials.Joint_46_Object_1_Material_1}
                                 skeleton={nodes.Joint_48_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_49_Object_0_SINGLE" geometry={nodes.Joint_49_Object_0_SINGLE.geometry}
                                 material={materials.Joint_46_Object_1_Material_1}
                                 skeleton={nodes.Joint_49_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_0_SINGLE" geometry={nodes.Joint_4_Object_0_SINGLE.geometry}
                                 material={materials.Joint_4_Object_0_Material_0}
                                 skeleton={nodes.Joint_4_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_5_Object_0_SINGLE" geometry={nodes.Joint_5_Object_0_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_5_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_6_Object_0_SINGLE" geometry={nodes.Joint_6_Object_0_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_6_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_8_Object_0_SINGLE" geometry={nodes.Joint_8_Object_0_SINGLE.geometry}
                                 material={materials.Joint_8_Object_0_Material_0}
                                 skeleton={nodes.Joint_8_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_9_Object_0_SINGLE" geometry={nodes.Joint_9_Object_0_SINGLE.geometry}
                                 material={materials.Joint_4_Object_0_Material_0}
                                 skeleton={nodes.Joint_9_Object_0_SINGLE.skeleton}/>
                </group>
                <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
                    <primitive object={nodes.JOBJ_0_1}/>
                    <skinnedMesh name="Joint_10_Object_0_SINGLE001"
                                 geometry={nodes.Joint_10_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_10_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_1_SINGLE" geometry={nodes.Joint_10_Object_1_SINGLE.geometry}
                                 material={materials.Joint_38_Object_0_Material_0}
                                 skeleton={nodes.Joint_10_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_2_SINGLE" geometry={nodes.Joint_10_Object_2_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_10_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_3_SINGLE" geometry={nodes.Joint_10_Object_3_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_10_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_4_SINGLE" geometry={nodes.Joint_10_Object_4_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_10_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_5_SINGLE" geometry={nodes.Joint_10_Object_5_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_10_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_6_SINGLE" geometry={nodes.Joint_10_Object_6_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_10_Object_6_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_0_SINGLE001"
                                 geometry={nodes.Joint_11_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_11_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_1_SINGLE" geometry={nodes.Joint_11_Object_1_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_11_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_2_SINGLE" geometry={nodes.Joint_11_Object_2_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_11_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_3_SINGLE" geometry={nodes.Joint_11_Object_3_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_11_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_4_SINGLE" geometry={nodes.Joint_11_Object_4_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_11_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_5_SINGLE" geometry={nodes.Joint_11_Object_5_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_11_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_6_SINGLE" geometry={nodes.Joint_11_Object_6_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_11_Object_6_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_0_SINGLE001"
                                 geometry={nodes.Joint_12_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_12_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_1_SINGLE" geometry={nodes.Joint_12_Object_1_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_12_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_2_SINGLE" geometry={nodes.Joint_12_Object_2_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_12_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_3_SINGLE" geometry={nodes.Joint_12_Object_3_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_12_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_4_SINGLE" geometry={nodes.Joint_12_Object_4_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_12_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_5_SINGLE" geometry={nodes.Joint_12_Object_5_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_12_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_14_Object_0_SINGLE001"
                                 geometry={nodes.Joint_14_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_14_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_15_Object_0_SINGLE001"
                                 geometry={nodes.Joint_15_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_15_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_0_SINGLE001"
                                 geometry={nodes.Joint_16_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_16_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_17_Object_0_SINGLE" geometry={nodes.Joint_17_Object_0_SINGLE.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_17_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_0_SINGLE001"
                                 geometry={nodes.Joint_18_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_18_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_19_Object_0_SINGLE001"
                                 geometry={nodes.Joint_19_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_19_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_0_SINGLE001" geometry={nodes.Joint_1_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_1_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_1_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_1_SINGLE" geometry={nodes.Joint_1_Object_1_SINGLE.geometry}
                                 material={materials.Joint_1_Object_1_Material_1}
                                 skeleton={nodes.Joint_1_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_2_SINGLE" geometry={nodes.Joint_1_Object_2_SINGLE.geometry}
                                 material={materials.Joint_1_Object_2_Material_2}
                                 skeleton={nodes.Joint_1_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_21_Object_0_SINGLE001"
                                 geometry={nodes.Joint_21_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_21_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_22_Object_0_SINGLE001"
                                 geometry={nodes.Joint_22_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_22_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_23_Object_0_SINGLE001"
                                 geometry={nodes.Joint_23_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_23_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_24_Object_0_SINGLE001"
                                 geometry={nodes.Joint_24_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_24_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_25_Object_0_SINGLE001"
                                 geometry={nodes.Joint_25_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_25_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_26_Object_0_SINGLE001"
                                 geometry={nodes.Joint_26_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_26_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_27_Object_0_SINGLE001"
                                 geometry={nodes.Joint_27_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_27_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_29_Object_0_SINGLE001"
                                 geometry={nodes.Joint_29_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_29_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_2_Object_0_SINGLE" geometry={nodes.Joint_2_Object_0_SINGLE.geometry}
                                 material={materials['Joint_1_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_2_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_2_Object_1_SINGLE" geometry={nodes.Joint_2_Object_1_SINGLE.geometry}
                                 material={materials.Joint_1_Object_1_Material_1}
                                 skeleton={nodes.Joint_2_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_2_Object_2_SINGLE" geometry={nodes.Joint_2_Object_2_SINGLE.geometry}
                                 material={materials.Joint_2_Object_2_Material_2}
                                 skeleton={nodes.Joint_2_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_30_Object_0_SINGLE001"
                                 geometry={nodes.Joint_30_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_30_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_31_Object_0_SINGLE001"
                                 geometry={nodes.Joint_31_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_31_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_32_Object_0_SINGLE001"
                                 geometry={nodes.Joint_32_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_32_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_32_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_33_Object_0_SINGLE001"
                                 geometry={nodes.Joint_33_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_33_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_34_Object_0_SINGLE001"
                                 geometry={nodes.Joint_34_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_34_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_35_Object_0_SINGLE001"
                                 geometry={nodes.Joint_35_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_35_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_35_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_35_Object_1_SINGLE" geometry={nodes.Joint_35_Object_1_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_35_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_35_Object_2_SINGLE" geometry={nodes.Joint_35_Object_2_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_35_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_35_Object_3_SINGLE" geometry={nodes.Joint_35_Object_3_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_35_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_0_SINGLE001"
                                 geometry={nodes.Joint_36_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_10_SINGLE" geometry={nodes.Joint_36_Object_10_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_10_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_11_SINGLE" geometry={nodes.Joint_36_Object_11_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_11_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_12_SINGLE" geometry={nodes.Joint_36_Object_12_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_12_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_13_SINGLE" geometry={nodes.Joint_36_Object_13_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_13_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_14_SINGLE" geometry={nodes.Joint_36_Object_14_SINGLE.geometry}
                                 material={materials.Joint_36_Object_14_Material_14}
                                 skeleton={nodes.Joint_36_Object_14_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_15_SINGLE" geometry={nodes.Joint_36_Object_15_SINGLE.geometry}
                                 material={materials.Joint_36_Object_15_Material_15}
                                 skeleton={nodes.Joint_36_Object_15_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_16_SINGLE" geometry={nodes.Joint_36_Object_16_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_16_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_17_SINGLE" geometry={nodes.Joint_36_Object_17_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_17_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_1_SINGLE" geometry={nodes.Joint_36_Object_1_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_2_SINGLE" geometry={nodes.Joint_36_Object_2_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_3_SINGLE" geometry={nodes.Joint_36_Object_3_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_4_SINGLE" geometry={nodes.Joint_36_Object_4_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_5_SINGLE" geometry={nodes.Joint_36_Object_5_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_6_SINGLE" geometry={nodes.Joint_36_Object_6_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_6_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_7_SINGLE" geometry={nodes.Joint_36_Object_7_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_7_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_8_SINGLE" geometry={nodes.Joint_36_Object_8_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_8_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_36_Object_9_SINGLE" geometry={nodes.Joint_36_Object_9_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_36_Object_9_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_38_Object_0_SINGLE001"
                                 geometry={nodes.Joint_38_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_38_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_39_Object_0_SINGLE001"
                                 geometry={nodes.Joint_39_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_39_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_0_SINGLE001" geometry={nodes.Joint_3_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_1_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_3_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_1_SINGLE" geometry={nodes.Joint_3_Object_1_SINGLE.geometry}
                                 material={materials.Joint_1_Object_1_Material_1}
                                 skeleton={nodes.Joint_3_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_2_SINGLE" geometry={nodes.Joint_3_Object_2_SINGLE.geometry}
                                 material={materials.Joint_2_Object_2_Material_2}
                                 skeleton={nodes.Joint_3_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_40_Object_0_SINGLE001"
                                 geometry={nodes.Joint_40_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_40_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_41_Object_0_SINGLE001"
                                 geometry={nodes.Joint_41_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_41_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_42_Object_0_SINGLE001"
                                 geometry={nodes.Joint_42_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_42_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_43_Object_0_SINGLE001"
                                 geometry={nodes.Joint_43_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_43_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_44_Object_0_SINGLE001"
                                 geometry={nodes.Joint_44_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_44_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_44_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_46_Object_0_SINGLE001"
                                 geometry={nodes.Joint_46_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_46_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_47_Object_0_SINGLE001"
                                 geometry={nodes.Joint_47_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_47_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_48_Object_0_SINGLE001"
                                 geometry={nodes.Joint_48_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_48_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_49_Object_0_SINGLE001"
                                 geometry={nodes.Joint_49_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_49_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_50_Object_0_SINGLE" geometry={nodes.Joint_50_Object_0_SINGLE.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_50_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_51_Object_0_SINGLE" geometry={nodes.Joint_51_Object_0_SINGLE.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_51_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_52_Object_0_SINGLE" geometry={nodes.Joint_52_Object_0_SINGLE.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_52_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_53_Object_0_SINGLE" geometry={nodes.Joint_53_Object_0_SINGLE.geometry}
                                 material={materials['Joint_44_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_53_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_54_Object_0_SINGLE" geometry={nodes.Joint_54_Object_0_SINGLE.geometry}
                                 material={materials['Joint_44_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_54_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_0_SINGLE" geometry={nodes.Joint_7_Object_0_SINGLE.geometry}
                                 material={materials.Joint_38_Object_0_Material_0}
                                 skeleton={nodes.Joint_7_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_10_SINGLE" geometry={nodes.Joint_7_Object_10_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_10_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_11_SINGLE" geometry={nodes.Joint_7_Object_11_SINGLE.geometry}
                                 material={materials.Joint_7_Object_11_Material_11}
                                 skeleton={nodes.Joint_7_Object_11_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_12_SINGLE" geometry={nodes.Joint_7_Object_12_SINGLE.geometry}
                                 material={materials.Joint_7_Object_12_Material_12}
                                 skeleton={nodes.Joint_7_Object_12_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_13_SINGLE" geometry={nodes.Joint_7_Object_13_SINGLE.geometry}
                                 material={materials.Joint_7_Object_11_Material_11}
                                 skeleton={nodes.Joint_7_Object_13_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_14_SINGLE" geometry={nodes.Joint_7_Object_14_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_14_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_15_SINGLE" geometry={nodes.Joint_7_Object_15_SINGLE.geometry}
                                 material={materials.Joint_7_Object_12_Material_12}
                                 skeleton={nodes.Joint_7_Object_15_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_16_SINGLE" geometry={nodes.Joint_7_Object_16_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_16_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_17_SINGLE" geometry={nodes.Joint_7_Object_17_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_17_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_18_SINGLE" geometry={nodes.Joint_7_Object_18_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_18_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_19_SINGLE" geometry={nodes.Joint_7_Object_19_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_19_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_1_SINGLE" geometry={nodes.Joint_7_Object_1_SINGLE.geometry}
                                 material={materials.Joint_7_Object_1_Material_1}
                                 skeleton={nodes.Joint_7_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_2_SINGLE" geometry={nodes.Joint_7_Object_2_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_3_SINGLE" geometry={nodes.Joint_7_Object_3_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_4_SINGLE" geometry={nodes.Joint_7_Object_4_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_5_SINGLE" geometry={nodes.Joint_7_Object_5_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_6_SINGLE" geometry={nodes.Joint_7_Object_6_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_6_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_7_SINGLE" geometry={nodes.Joint_7_Object_7_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_7_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_8_SINGLE" geometry={nodes.Joint_7_Object_8_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_8_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_9_SINGLE" geometry={nodes.Joint_7_Object_9_SINGLE.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_7_Object_9_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_8_Object_0_SINGLE001" geometry={nodes.Joint_8_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_10_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_8_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_9_Object_0_SINGLE001" geometry={nodes.Joint_9_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_9_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_9_Object_0_SINGLE001.skeleton}/>
                </group>
                <group name="Armature002" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Vert001" position={[46.75, 0, -7]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh name="water_top_1" geometry={nodes.water_top_1.geometry} material={materials.particle_top}
                              position={[3.39, 21.47, 8.19]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_2" geometry={nodes.water_top_2.geometry} material={materials.particle_top}
                              position={[7.66, 21.4, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_3" geometry={nodes.water_top_3.geometry} material={materials.particle_top}
                              position={[2.47, 21.31, -5.95]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_4" geometry={nodes.water_top_4.geometry} material={materials.particle_top}
                              position={[3.7, 21.17, -3.7]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_5" geometry={nodes.water_top_5.geometry} material={materials.particle_top}
                              position={[-3.34, 21, 2.23]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_6" geometry={nodes.water_top_6.geometry} material={materials.particle_top}
                              position={[-1.08, 20.76, -2.6]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_7" geometry={nodes.water_top_7.geometry} material={materials.particle_top}
                              position={[1.57, 20.51, 0.31]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                    </group>
                    <primitive object={nodes.JOBJ_0_2}/>
                    <skinnedMesh name="Joint_0_Object_0002" geometry={nodes.Joint_0_Object_0002.geometry}
                                 material={materials['Joint_0_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_0_Object_0002.skeleton}/>
                </group>
                <group name="Vert002" position={[47, -18.26, 0]}>
                    <mesh name="water_bot_1" geometry={nodes.water_bot_1.geometry} material={materials.particle_top}
                          position={[2.82, 21.15, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                    <mesh name="water_bot_2" geometry={nodes.water_bot_2.geometry} material={materials.particle_top}
                          position={[0.38, 20.53, -0.92]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                </group>
                <group name="Armature001" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Vert" position={[-47, 0, -13]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh name="water_top_8" geometry={nodes.water_top_8.geometry} material={materials.particle_top}
                              position={[3.39, 1.23, 8.19]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_9" geometry={nodes.water_top_9.geometry} material={materials.particle_top}
                              position={[7.66, 1.16, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_10" geometry={nodes.water_top_10.geometry}
                              material={materials.particle_top} position={[2.47, 1.07, -5.95]}
                              rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_11" geometry={nodes.water_top_11.geometry}
                              material={materials.particle_top} position={[3.7, 0.93, -3.7]}
                              rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_12" geometry={nodes.water_top_12.geometry}
                              material={materials.particle_top} position={[-3.34, 0.76, 2.23]}
                              rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_13" geometry={nodes.water_top_13.geometry}
                              material={materials.particle_top} position={[-1.08, 0.52, -2.6]}
                              rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                        <mesh name="water_top_14" geometry={nodes.water_top_14.geometry}
                              material={materials.particle_top} position={[1.57, 0.27, 0.31]}
                              rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                    </group>
                    <primitive object={nodes.JOBJ_0_3}/>
                    <skinnedMesh name="Joint_0_Object_0001" geometry={nodes.Joint_0_Object_0001.geometry}
                                 material={materials['Joint_0_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_0_Object_0001.skeleton}/>
                </group>
                <group name="Vert003" position={[-47, 1.98, 0]}>
                    <mesh name="water_bot_3" geometry={nodes.water_bot_3.geometry} material={materials.particle_top}
                          position={[2.82, 0.91, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                    <mesh name="water_bot_4" geometry={nodes.water_bot_4.geometry} material={materials.particle_top}
                          position={[0.38, 0.29, -0.92]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}/>
                </group>
                <mesh name="Sphere_instance" geometry={nodes.Sphere_instance.geometry} material={materials.Material}/>
                <mesh name="water_top" geometry={nodes.water_top.geometry} material={materials.particle_top}
                      rotation={[Math.PI / 2, 0, 0]}/>
                <mesh name="water_bot" geometry={nodes.water_bot.geometry} material={materials.particle_top}
                      rotation={[Math.PI / 2, 0, 0]}/>
                <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} scale={2040.8}/>
            </group>
        </group>
    )
}

useGLTF.preload('/Fountain_render-transformed.glb')
