/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/HomeRunStadium.glb --types --keepnames --transform
*/

import * as THREE from 'three'
import React from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Joint_1_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_1_Object_1_SINGLE: THREE.SkinnedMesh
    Joint_1_Object_2_SINGLE: THREE.SkinnedMesh
    Joint_1_Object_3_SINGLE: THREE.SkinnedMesh
    Joint_1_Object_4_SINGLE: THREE.SkinnedMesh
    Joint_1_Object_5_SINGLE: THREE.SkinnedMesh
    Joint_1_Object_6_SINGLE: THREE.SkinnedMesh
    Joint_1_Object_7_SINGLE: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_4_Object_1_SINGLE: THREE.SkinnedMesh
    Joint_4_Object_2_SINGLE: THREE.SkinnedMesh
    Joint_10_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_11_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_11_Object_1_SINGLE: THREE.SkinnedMesh
    Joint_11_Object_2_SINGLE: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_2_Object_1_SINGLE001: THREE.SkinnedMesh
    Joint_2_Object_2_SINGLE: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_3_Object_1_SINGLE: THREE.SkinnedMesh
    Joint_3_Object_2_SINGLE: THREE.SkinnedMesh
    Joint_3_Object_3_SINGLE: THREE.SkinnedMesh
    Joint_3_Object_4_SINGLE: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_4_Object_1_SINGLE001: THREE.SkinnedMesh
    Joint_5_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_6_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_7_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_8_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_9_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_1_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_1_Object_1_SINGLE001: THREE.SkinnedMesh
    Joint_1_Object_2_SINGLE001: THREE.SkinnedMesh
    Joint_1_Object_3_SINGLE001: THREE.SkinnedMesh
    Joint_1_Object_4_SINGLE001: THREE.SkinnedMesh
    Joint_1_Object_5_SINGLE001: THREE.SkinnedMesh
    Joint_1_Object_6_SINGLE001: THREE.SkinnedMesh
    Joint_1_Object_7_SINGLE001: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_4_Object_1_SINGLE002: THREE.SkinnedMesh
    Joint_4_Object_2_SINGLE001: THREE.SkinnedMesh
    Joint_10_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_11_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_11_Object_1_SINGLE001: THREE.SkinnedMesh
    Joint_11_Object_2_SINGLE001: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE005: THREE.SkinnedMesh
    Joint_2_Object_1_SINGLE002: THREE.SkinnedMesh
    Joint_2_Object_2_SINGLE001: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_3_Object_1_SINGLE001: THREE.SkinnedMesh
    Joint_3_Object_2_SINGLE001: THREE.SkinnedMesh
    Joint_3_Object_3_SINGLE001: THREE.SkinnedMesh
    Joint_3_Object_4_SINGLE001: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_4_Object_1_SINGLE003: THREE.SkinnedMesh
    Joint_5_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_6_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_7_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_8_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_9_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_1_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_1_Object_1_SINGLE002: THREE.SkinnedMesh
    Joint_1_Object_2_SINGLE002: THREE.SkinnedMesh
    Joint_1_Object_3_SINGLE002: THREE.SkinnedMesh
    Joint_1_Object_4_SINGLE002: THREE.SkinnedMesh
    Joint_1_Object_5_SINGLE002: THREE.SkinnedMesh
    Joint_1_Object_6_SINGLE002: THREE.SkinnedMesh
    Joint_1_Object_7_SINGLE002: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE006: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE005: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE005: THREE.SkinnedMesh
    Joint_4_Object_1_SINGLE004: THREE.SkinnedMesh
    Joint_4_Object_2_SINGLE002: THREE.SkinnedMesh
    Joint_10_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_11_Object_0_SINGLE002: THREE.SkinnedMesh
    Joint_11_Object_1_SINGLE002: THREE.SkinnedMesh
    Joint_11_Object_2_SINGLE002: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE007: THREE.SkinnedMesh
    Joint_2_Object_1_SINGLE003: THREE.SkinnedMesh
    Joint_2_Object_2_SINGLE002: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE006: THREE.SkinnedMesh
    Joint_3_Object_1_SINGLE002: THREE.SkinnedMesh
    Joint_3_Object_2_SINGLE002: THREE.SkinnedMesh
    Joint_3_Object_3_SINGLE002: THREE.SkinnedMesh
    Joint_3_Object_4_SINGLE002: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE006: THREE.SkinnedMesh
    Joint_4_Object_1_SINGLE005: THREE.SkinnedMesh
    Joint_5_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_6_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_7_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_8_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_9_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_1_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_1_Object_1_SINGLE003: THREE.SkinnedMesh
    Joint_1_Object_2_SINGLE003: THREE.SkinnedMesh
    Joint_1_Object_3_SINGLE003: THREE.SkinnedMesh
    Joint_1_Object_4_SINGLE003: THREE.SkinnedMesh
    Joint_1_Object_5_SINGLE003: THREE.SkinnedMesh
    Joint_1_Object_6_SINGLE003: THREE.SkinnedMesh
    Joint_1_Object_7_SINGLE003: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE008: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE007: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE007: THREE.SkinnedMesh
    Joint_4_Object_1_SINGLE006: THREE.SkinnedMesh
    Joint_4_Object_2_SINGLE003: THREE.SkinnedMesh
    Joint_10_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_11_Object_0_SINGLE003: THREE.SkinnedMesh
    Joint_11_Object_1_SINGLE003: THREE.SkinnedMesh
    Joint_11_Object_2_SINGLE003: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE009: THREE.SkinnedMesh
    Joint_2_Object_1_SINGLE004: THREE.SkinnedMesh
    Joint_2_Object_2_SINGLE003: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE008: THREE.SkinnedMesh
    Joint_3_Object_1_SINGLE003: THREE.SkinnedMesh
    Joint_3_Object_2_SINGLE003: THREE.SkinnedMesh
    Joint_3_Object_3_SINGLE003: THREE.SkinnedMesh
    Joint_3_Object_4_SINGLE003: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE008: THREE.SkinnedMesh
    Joint_4_Object_1_SINGLE007: THREE.SkinnedMesh
    Joint_5_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_6_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_7_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_8_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_9_Object_0_SINGLE004: THREE.SkinnedMesh
    Joint_1_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE001: THREE.SkinnedMesh
    Joint_3_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_4_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_5_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_6_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_7_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_8_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_9_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_2_Object_0_SINGLE: THREE.SkinnedMesh
    Joint_2_Object_1_SINGLE: THREE.SkinnedMesh
    Cube: THREE.Mesh
    Joint_0_Object_0: THREE.Mesh
    Joint_0_Object_1: THREE.Mesh
    Joint_0_Object_2: THREE.Mesh
    Joint_0_Object_3: THREE.Mesh
    Joint_0_Object_4: THREE.Mesh
    Joint_0_Object_5: THREE.Mesh
    Joint_0_Object_6: THREE.Mesh
    Joint_0_Object_7: THREE.Mesh
    Joint_0_Object_8: THREE.Mesh
    Joint_0_Object_9: THREE.Mesh
    Joint_0_Object_10: THREE.Mesh
    Joint_0_Object_11: THREE.Mesh
    Joint_0_Object_12: THREE.Mesh
    Joint_0_Object_13: THREE.Mesh
    Joint_0_Object_14: THREE.Mesh
    Joint_0_Object_15: THREE.Mesh
    Joint_0_Object_16: THREE.Mesh
    Joint_0_Object_17: THREE.Mesh
    Joint_0_Object_18: THREE.Mesh
    Joint_0_Object_19: THREE.Mesh
    Joint_0_Object_20: THREE.Mesh
    Joint_0_Object_21: THREE.Mesh
    Joint_0_Object_22: THREE.Mesh
    Joint_0_Object_23: THREE.Mesh
    Joint_0_Object_24: THREE.Mesh
    Joint_0_Object_25: THREE.Mesh
    Joint_0_Object_26: THREE.Mesh
    Joint_0_Object_27: THREE.Mesh
    Joint_0_Object_28: THREE.Mesh
    Joint_0_Object_29: THREE.Mesh
    Joint_0_Object_30: THREE.Mesh
    Joint_0_Object_31: THREE.Mesh
    Joint_0_Object_32: THREE.Mesh
    Joint_0_Object_33: THREE.Mesh
    Joint_0_Object_34: THREE.Mesh
    Joint_0_Object_35: THREE.Mesh
    Joint_0_Object_36: THREE.Mesh
    Joint_0_Object_37: THREE.Mesh
    Joint_0_Object_38: THREE.Mesh
    Joint_0_Object_39: THREE.Mesh
    Joint_0_Object_40: THREE.Mesh
    Joint_0_Object_41: THREE.Mesh
    JOBJ_0: THREE.Bone
    JOBJ_0_1: THREE.Bone
    JOBJ_0_2: THREE.Bone
    JOBJ_0_3: THREE.Bone
    JOBJ_0_4: THREE.Bone
    JOBJ_0_5: THREE.Bone
    JOBJ_0_6: THREE.Bone
    JOBJ_0_7: THREE.Bone
    JOBJ_0_8: THREE.Bone
    JOBJ_0_9: THREE.Bone
  }
  materials: {
    ['Joint_1_Object_0_Material_0.001']: THREE.MeshBasicMaterial
    Joint_1_Object_1_Material_1: THREE.MeshBasicMaterial
    Joint_1_Object_2_Material_2: THREE.MeshBasicMaterial
    Joint_1_Object_3_Material_3: THREE.MeshBasicMaterial
    Joint_1_Object_4_Material_4: THREE.MeshBasicMaterial
    Joint_1_Object_5_Material_5: THREE.MeshBasicMaterial
    ['Joint_2_Object_0_Material_0.002']: THREE.MeshStandardMaterial
    ['Joint_3_Object_0_Material_0.001']: THREE.MeshBasicMaterial
    ['Joint_4_Object_0_Material_0.001']: THREE.MeshBasicMaterial
    Joint_4_Object_1_Material_1: THREE.MeshBasicMaterial
    Joint_4_Object_2_Material_2: THREE.MeshBasicMaterial
    Joint_3_Object_2_Material_2: THREE.MeshBasicMaterial
    ['Joint_4_Object_0_Material_0.002']: THREE.MeshStandardMaterial
    ['Joint_4_Object_1_Material_1.001']: THREE.MeshStandardMaterial
    ['Joint_5_Object_0_Material_0.001']: THREE.MeshStandardMaterial
    ['Joint_7_Object_0_Material_0.001']: THREE.MeshStandardMaterial
    ['Joint_4_Object_1_Material_1.002']: THREE.MeshBasicMaterial
    ['Joint_4_Object_1_Material_1.003']: THREE.MeshBasicMaterial
    ['Joint_4_Object_1_Material_1.004']: THREE.MeshBasicMaterial
    Joint_1_Object_0_Material_0: THREE.MeshBasicMaterial
    ['Joint_2_Object_0_Material_0.001']: THREE.MeshBasicMaterial
    Joint_3_Object_0_Material_0: THREE.MeshBasicMaterial
    Joint_2_Object_0_Material_0: THREE.MeshBasicMaterial
    Joint_2_Object_1_Material_1: THREE.MeshBasicMaterial
    Material: THREE.MeshBasicMaterial
    Joint_0_Object_0_Material_0: THREE.MeshBasicMaterial
    ['Joint_1_Object_0_Material_0.001']: THREE.MeshBasicMaterial
    ['Joint_5_Object_0_Material_0.001']: THREE.MeshStandardMaterial
    ['Joint_4_Object_0_Material_0.002']: THREE.MeshStandardMaterial
    ['Joint_4_Object_1_Material_1.001']: THREE.MeshStandardMaterial
    Joint_0_Object_31_Material_31: THREE.MeshStandardMaterial
    Joint_0_Object_32_Material_32: THREE.MeshStandardMaterial
    Joint_0_Object_33_Material_33: THREE.MeshBasicMaterial
    Joint_0_Object_34_Material_34: THREE.MeshBasicMaterial
    ['Joint_4_Object_0_Material_0.001']: THREE.MeshBasicMaterial
    Joint_0_Object_36_Material_36: THREE.MeshBasicMaterial
    Joint_0_Object_37_Material_37: THREE.MeshBasicMaterial
    ['Joint_7_Object_0_Material_0.001']: THREE.MeshStandardMaterial
    ['Joint_2_Object_0_Material_0.002']: THREE.MeshStandardMaterial
  }
}

export function HomeRunStadium(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/HomeRunStadium-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Armature002" rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0} />
        <skinnedMesh name="Joint_1_Object_0_SINGLE001" geometry={nodes.Joint_1_Object_0_SINGLE001.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_1_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_1_Object_1_SINGLE" geometry={nodes.Joint_1_Object_1_SINGLE.geometry} material={materials.Joint_1_Object_1_Material_1} skeleton={nodes.Joint_1_Object_1_SINGLE.skeleton} />
        <skinnedMesh name="Joint_1_Object_2_SINGLE" geometry={nodes.Joint_1_Object_2_SINGLE.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_1_Object_2_SINGLE.skeleton} />
        <skinnedMesh name="Joint_1_Object_3_SINGLE" geometry={nodes.Joint_1_Object_3_SINGLE.geometry} material={materials.Joint_1_Object_3_Material_3} skeleton={nodes.Joint_1_Object_3_SINGLE.skeleton} />
        <skinnedMesh name="Joint_1_Object_4_SINGLE" geometry={nodes.Joint_1_Object_4_SINGLE.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_1_Object_4_SINGLE.skeleton} />
        <skinnedMesh name="Joint_1_Object_5_SINGLE" geometry={nodes.Joint_1_Object_5_SINGLE.geometry} material={materials.Joint_1_Object_5_Material_5} skeleton={nodes.Joint_1_Object_5_SINGLE.skeleton} />
        <skinnedMesh name="Joint_1_Object_6_SINGLE" geometry={nodes.Joint_1_Object_6_SINGLE.geometry} material={materials.Joint_1_Object_5_Material_5} skeleton={nodes.Joint_1_Object_6_SINGLE.skeleton} />
        <skinnedMesh name="Joint_1_Object_7_SINGLE" geometry={nodes.Joint_1_Object_7_SINGLE.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_1_Object_7_SINGLE.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE002" geometry={nodes.Joint_2_Object_0_SINGLE002.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_2_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE001" geometry={nodes.Joint_3_Object_0_SINGLE001.geometry} material={materials['Joint_3_Object_0_Material_0.001']} skeleton={nodes.Joint_3_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE001" geometry={nodes.Joint_4_Object_0_SINGLE001.geometry} material={materials['Joint_4_Object_0_Material_0.001']} skeleton={nodes.Joint_4_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_4_Object_1_SINGLE" geometry={nodes.Joint_4_Object_1_SINGLE.geometry} material={materials.Joint_4_Object_1_Material_1} skeleton={nodes.Joint_4_Object_1_SINGLE.skeleton} />
        <skinnedMesh name="Joint_4_Object_2_SINGLE" geometry={nodes.Joint_4_Object_2_SINGLE.geometry} material={materials.Joint_4_Object_2_Material_2} skeleton={nodes.Joint_4_Object_2_SINGLE.skeleton} />
      </group>
      <group name="Armature003" rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_1} />
        <skinnedMesh name="Joint_10_Object_0_SINGLE" geometry={nodes.Joint_10_Object_0_SINGLE.geometry} material={materials['Joint_3_Object_0_Material_0.001']} skeleton={nodes.Joint_10_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_11_Object_0_SINGLE" geometry={nodes.Joint_11_Object_0_SINGLE.geometry} material={materials['Joint_4_Object_0_Material_0.001']} skeleton={nodes.Joint_11_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_11_Object_1_SINGLE" geometry={nodes.Joint_11_Object_1_SINGLE.geometry} material={materials.Joint_4_Object_1_Material_1} skeleton={nodes.Joint_11_Object_1_SINGLE.skeleton} />
        <skinnedMesh name="Joint_11_Object_2_SINGLE" geometry={nodes.Joint_11_Object_2_SINGLE.geometry} material={materials.Joint_4_Object_2_Material_2} skeleton={nodes.Joint_11_Object_2_SINGLE.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE003" geometry={nodes.Joint_2_Object_0_SINGLE003.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_2_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_2_Object_1_SINGLE001" geometry={nodes.Joint_2_Object_1_SINGLE001.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_2_Object_1_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_2_Object_2_SINGLE" geometry={nodes.Joint_2_Object_2_SINGLE.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_2_Object_2_SINGLE.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE002" geometry={nodes.Joint_3_Object_0_SINGLE002.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_3_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_3_Object_1_SINGLE" geometry={nodes.Joint_3_Object_1_SINGLE.geometry} material={materials.Joint_1_Object_1_Material_1} skeleton={nodes.Joint_3_Object_1_SINGLE.skeleton} />
        <skinnedMesh name="Joint_3_Object_2_SINGLE" geometry={nodes.Joint_3_Object_2_SINGLE.geometry} material={materials.Joint_3_Object_2_Material_2} skeleton={nodes.Joint_3_Object_2_SINGLE.skeleton} />
        <skinnedMesh name="Joint_3_Object_3_SINGLE" geometry={nodes.Joint_3_Object_3_SINGLE.geometry} material={materials.Joint_1_Object_3_Material_3} skeleton={nodes.Joint_3_Object_3_SINGLE.skeleton} />
        <skinnedMesh name="Joint_3_Object_4_SINGLE" geometry={nodes.Joint_3_Object_4_SINGLE.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_3_Object_4_SINGLE.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE002" geometry={nodes.Joint_4_Object_0_SINGLE002.geometry} material={materials['Joint_4_Object_0_Material_0.002']} skeleton={nodes.Joint_4_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_4_Object_1_SINGLE001" geometry={nodes.Joint_4_Object_1_SINGLE001.geometry} material={materials['Joint_4_Object_1_Material_1.001']} skeleton={nodes.Joint_4_Object_1_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_5_Object_0_SINGLE001" geometry={nodes.Joint_5_Object_0_SINGLE001.geometry} material={materials['Joint_5_Object_0_Material_0.001']} skeleton={nodes.Joint_5_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_6_Object_0_SINGLE001" geometry={nodes.Joint_6_Object_0_SINGLE001.geometry} material={materials['Joint_5_Object_0_Material_0.001']} skeleton={nodes.Joint_6_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_7_Object_0_SINGLE001" geometry={nodes.Joint_7_Object_0_SINGLE001.geometry} material={materials['Joint_7_Object_0_Material_0.001']} skeleton={nodes.Joint_7_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_8_Object_0_SINGLE001" geometry={nodes.Joint_8_Object_0_SINGLE001.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_8_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_9_Object_0_SINGLE001" geometry={nodes.Joint_9_Object_0_SINGLE001.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_9_Object_0_SINGLE001.skeleton} />
      </group>
      <group name="Armature004" position={[320, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_2} />
        <skinnedMesh name="Joint_1_Object_0_SINGLE002" geometry={nodes.Joint_1_Object_0_SINGLE002.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_1_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_1_Object_1_SINGLE001" geometry={nodes.Joint_1_Object_1_SINGLE001.geometry} material={materials.Joint_1_Object_1_Material_1} skeleton={nodes.Joint_1_Object_1_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_1_Object_2_SINGLE001" geometry={nodes.Joint_1_Object_2_SINGLE001.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_1_Object_2_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_1_Object_3_SINGLE001" geometry={nodes.Joint_1_Object_3_SINGLE001.geometry} material={materials.Joint_1_Object_3_Material_3} skeleton={nodes.Joint_1_Object_3_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_1_Object_4_SINGLE001" geometry={nodes.Joint_1_Object_4_SINGLE001.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_1_Object_4_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_1_Object_5_SINGLE001" geometry={nodes.Joint_1_Object_5_SINGLE001.geometry} material={materials.Joint_1_Object_5_Material_5} skeleton={nodes.Joint_1_Object_5_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_1_Object_6_SINGLE001" geometry={nodes.Joint_1_Object_6_SINGLE001.geometry} material={materials.Joint_1_Object_5_Material_5} skeleton={nodes.Joint_1_Object_6_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_1_Object_7_SINGLE001" geometry={nodes.Joint_1_Object_7_SINGLE001.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_1_Object_7_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE004" geometry={nodes.Joint_2_Object_0_SINGLE004.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_2_Object_0_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE003" geometry={nodes.Joint_3_Object_0_SINGLE003.geometry} material={materials['Joint_3_Object_0_Material_0.001']} skeleton={nodes.Joint_3_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE003" geometry={nodes.Joint_4_Object_0_SINGLE003.geometry} material={materials['Joint_4_Object_0_Material_0.001']} skeleton={nodes.Joint_4_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_4_Object_1_SINGLE002" geometry={nodes.Joint_4_Object_1_SINGLE002.geometry} material={materials['Joint_4_Object_1_Material_1.002']} skeleton={nodes.Joint_4_Object_1_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_4_Object_2_SINGLE001" geometry={nodes.Joint_4_Object_2_SINGLE001.geometry} material={materials.Joint_4_Object_2_Material_2} skeleton={nodes.Joint_4_Object_2_SINGLE001.skeleton} />
      </group>
      <group name="Armature005" position={[320, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_3} />
        <skinnedMesh name="Joint_10_Object_0_SINGLE001" geometry={nodes.Joint_10_Object_0_SINGLE001.geometry} material={materials['Joint_3_Object_0_Material_0.001']} skeleton={nodes.Joint_10_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_11_Object_0_SINGLE001" geometry={nodes.Joint_11_Object_0_SINGLE001.geometry} material={materials['Joint_4_Object_0_Material_0.001']} skeleton={nodes.Joint_11_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_11_Object_1_SINGLE001" geometry={nodes.Joint_11_Object_1_SINGLE001.geometry} material={materials['Joint_4_Object_1_Material_1.002']} skeleton={nodes.Joint_11_Object_1_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_11_Object_2_SINGLE001" geometry={nodes.Joint_11_Object_2_SINGLE001.geometry} material={materials.Joint_4_Object_2_Material_2} skeleton={nodes.Joint_11_Object_2_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE005" geometry={nodes.Joint_2_Object_0_SINGLE005.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_2_Object_0_SINGLE005.skeleton} />
        <skinnedMesh name="Joint_2_Object_1_SINGLE002" geometry={nodes.Joint_2_Object_1_SINGLE002.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_2_Object_1_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_2_Object_2_SINGLE001" geometry={nodes.Joint_2_Object_2_SINGLE001.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_2_Object_2_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE004" geometry={nodes.Joint_3_Object_0_SINGLE004.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_3_Object_0_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_3_Object_1_SINGLE001" geometry={nodes.Joint_3_Object_1_SINGLE001.geometry} material={materials.Joint_1_Object_1_Material_1} skeleton={nodes.Joint_3_Object_1_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_3_Object_2_SINGLE001" geometry={nodes.Joint_3_Object_2_SINGLE001.geometry} material={materials.Joint_3_Object_2_Material_2} skeleton={nodes.Joint_3_Object_2_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_3_Object_3_SINGLE001" geometry={nodes.Joint_3_Object_3_SINGLE001.geometry} material={materials.Joint_1_Object_3_Material_3} skeleton={nodes.Joint_3_Object_3_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_3_Object_4_SINGLE001" geometry={nodes.Joint_3_Object_4_SINGLE001.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_3_Object_4_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE004" geometry={nodes.Joint_4_Object_0_SINGLE004.geometry} material={materials['Joint_4_Object_0_Material_0.002']} skeleton={nodes.Joint_4_Object_0_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_4_Object_1_SINGLE003" geometry={nodes.Joint_4_Object_1_SINGLE003.geometry} material={materials['Joint_4_Object_1_Material_1.001']} skeleton={nodes.Joint_4_Object_1_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_5_Object_0_SINGLE002" geometry={nodes.Joint_5_Object_0_SINGLE002.geometry} material={materials['Joint_5_Object_0_Material_0.001']} skeleton={nodes.Joint_5_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_6_Object_0_SINGLE002" geometry={nodes.Joint_6_Object_0_SINGLE002.geometry} material={materials['Joint_5_Object_0_Material_0.001']} skeleton={nodes.Joint_6_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_7_Object_0_SINGLE002" geometry={nodes.Joint_7_Object_0_SINGLE002.geometry} material={materials['Joint_7_Object_0_Material_0.001']} skeleton={nodes.Joint_7_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_8_Object_0_SINGLE002" geometry={nodes.Joint_8_Object_0_SINGLE002.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_8_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_9_Object_0_SINGLE002" geometry={nodes.Joint_9_Object_0_SINGLE002.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_9_Object_0_SINGLE002.skeleton} />
      </group>
      <group name="Armature006" position={[640, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_4} />
        <skinnedMesh name="Joint_1_Object_0_SINGLE003" geometry={nodes.Joint_1_Object_0_SINGLE003.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_1_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_1_Object_1_SINGLE002" geometry={nodes.Joint_1_Object_1_SINGLE002.geometry} material={materials.Joint_1_Object_1_Material_1} skeleton={nodes.Joint_1_Object_1_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_1_Object_2_SINGLE002" geometry={nodes.Joint_1_Object_2_SINGLE002.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_1_Object_2_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_1_Object_3_SINGLE002" geometry={nodes.Joint_1_Object_3_SINGLE002.geometry} material={materials.Joint_1_Object_3_Material_3} skeleton={nodes.Joint_1_Object_3_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_1_Object_4_SINGLE002" geometry={nodes.Joint_1_Object_4_SINGLE002.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_1_Object_4_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_1_Object_5_SINGLE002" geometry={nodes.Joint_1_Object_5_SINGLE002.geometry} material={materials.Joint_1_Object_5_Material_5} skeleton={nodes.Joint_1_Object_5_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_1_Object_6_SINGLE002" geometry={nodes.Joint_1_Object_6_SINGLE002.geometry} material={materials.Joint_1_Object_5_Material_5} skeleton={nodes.Joint_1_Object_6_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_1_Object_7_SINGLE002" geometry={nodes.Joint_1_Object_7_SINGLE002.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_1_Object_7_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE006" geometry={nodes.Joint_2_Object_0_SINGLE006.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_2_Object_0_SINGLE006.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE005" geometry={nodes.Joint_3_Object_0_SINGLE005.geometry} material={materials['Joint_3_Object_0_Material_0.001']} skeleton={nodes.Joint_3_Object_0_SINGLE005.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE005" geometry={nodes.Joint_4_Object_0_SINGLE005.geometry} material={materials['Joint_4_Object_0_Material_0.001']} skeleton={nodes.Joint_4_Object_0_SINGLE005.skeleton} />
        <skinnedMesh name="Joint_4_Object_1_SINGLE004" geometry={nodes.Joint_4_Object_1_SINGLE004.geometry} material={materials['Joint_4_Object_1_Material_1.003']} skeleton={nodes.Joint_4_Object_1_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_4_Object_2_SINGLE002" geometry={nodes.Joint_4_Object_2_SINGLE002.geometry} material={materials.Joint_4_Object_2_Material_2} skeleton={nodes.Joint_4_Object_2_SINGLE002.skeleton} />
      </group>
      <group name="Armature007" position={[640, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_5} />
        <skinnedMesh name="Joint_10_Object_0_SINGLE002" geometry={nodes.Joint_10_Object_0_SINGLE002.geometry} material={materials['Joint_3_Object_0_Material_0.001']} skeleton={nodes.Joint_10_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_11_Object_0_SINGLE002" geometry={nodes.Joint_11_Object_0_SINGLE002.geometry} material={materials['Joint_4_Object_0_Material_0.001']} skeleton={nodes.Joint_11_Object_0_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_11_Object_1_SINGLE002" geometry={nodes.Joint_11_Object_1_SINGLE002.geometry} material={materials['Joint_4_Object_1_Material_1.003']} skeleton={nodes.Joint_11_Object_1_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_11_Object_2_SINGLE002" geometry={nodes.Joint_11_Object_2_SINGLE002.geometry} material={materials.Joint_4_Object_2_Material_2} skeleton={nodes.Joint_11_Object_2_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE007" geometry={nodes.Joint_2_Object_0_SINGLE007.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_2_Object_0_SINGLE007.skeleton} />
        <skinnedMesh name="Joint_2_Object_1_SINGLE003" geometry={nodes.Joint_2_Object_1_SINGLE003.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_2_Object_1_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_2_Object_2_SINGLE002" geometry={nodes.Joint_2_Object_2_SINGLE002.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_2_Object_2_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE006" geometry={nodes.Joint_3_Object_0_SINGLE006.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_3_Object_0_SINGLE006.skeleton} />
        <skinnedMesh name="Joint_3_Object_1_SINGLE002" geometry={nodes.Joint_3_Object_1_SINGLE002.geometry} material={materials.Joint_1_Object_1_Material_1} skeleton={nodes.Joint_3_Object_1_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_3_Object_2_SINGLE002" geometry={nodes.Joint_3_Object_2_SINGLE002.geometry} material={materials.Joint_3_Object_2_Material_2} skeleton={nodes.Joint_3_Object_2_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_3_Object_3_SINGLE002" geometry={nodes.Joint_3_Object_3_SINGLE002.geometry} material={materials.Joint_1_Object_3_Material_3} skeleton={nodes.Joint_3_Object_3_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_3_Object_4_SINGLE002" geometry={nodes.Joint_3_Object_4_SINGLE002.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_3_Object_4_SINGLE002.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE006" geometry={nodes.Joint_4_Object_0_SINGLE006.geometry} material={materials['Joint_4_Object_0_Material_0.002']} skeleton={nodes.Joint_4_Object_0_SINGLE006.skeleton} />
        <skinnedMesh name="Joint_4_Object_1_SINGLE005" geometry={nodes.Joint_4_Object_1_SINGLE005.geometry} material={materials['Joint_4_Object_1_Material_1.001']} skeleton={nodes.Joint_4_Object_1_SINGLE005.skeleton} />
        <skinnedMesh name="Joint_5_Object_0_SINGLE003" geometry={nodes.Joint_5_Object_0_SINGLE003.geometry} material={materials['Joint_5_Object_0_Material_0.001']} skeleton={nodes.Joint_5_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_6_Object_0_SINGLE003" geometry={nodes.Joint_6_Object_0_SINGLE003.geometry} material={materials['Joint_5_Object_0_Material_0.001']} skeleton={nodes.Joint_6_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_7_Object_0_SINGLE003" geometry={nodes.Joint_7_Object_0_SINGLE003.geometry} material={materials['Joint_7_Object_0_Material_0.001']} skeleton={nodes.Joint_7_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_8_Object_0_SINGLE003" geometry={nodes.Joint_8_Object_0_SINGLE003.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_8_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_9_Object_0_SINGLE003" geometry={nodes.Joint_9_Object_0_SINGLE003.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_9_Object_0_SINGLE003.skeleton} />
      </group>
      <group name="Armature008" position={[960, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_6} />
        <skinnedMesh name="Joint_1_Object_0_SINGLE004" geometry={nodes.Joint_1_Object_0_SINGLE004.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_1_Object_0_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_1_Object_1_SINGLE003" geometry={nodes.Joint_1_Object_1_SINGLE003.geometry} material={materials.Joint_1_Object_1_Material_1} skeleton={nodes.Joint_1_Object_1_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_1_Object_2_SINGLE003" geometry={nodes.Joint_1_Object_2_SINGLE003.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_1_Object_2_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_1_Object_3_SINGLE003" geometry={nodes.Joint_1_Object_3_SINGLE003.geometry} material={materials.Joint_1_Object_3_Material_3} skeleton={nodes.Joint_1_Object_3_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_1_Object_4_SINGLE003" geometry={nodes.Joint_1_Object_4_SINGLE003.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_1_Object_4_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_1_Object_5_SINGLE003" geometry={nodes.Joint_1_Object_5_SINGLE003.geometry} material={materials.Joint_1_Object_5_Material_5} skeleton={nodes.Joint_1_Object_5_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_1_Object_6_SINGLE003" geometry={nodes.Joint_1_Object_6_SINGLE003.geometry} material={materials.Joint_1_Object_5_Material_5} skeleton={nodes.Joint_1_Object_6_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_1_Object_7_SINGLE003" geometry={nodes.Joint_1_Object_7_SINGLE003.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_1_Object_7_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE008" geometry={nodes.Joint_2_Object_0_SINGLE008.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_2_Object_0_SINGLE008.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE007" geometry={nodes.Joint_3_Object_0_SINGLE007.geometry} material={materials['Joint_3_Object_0_Material_0.001']} skeleton={nodes.Joint_3_Object_0_SINGLE007.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE007" geometry={nodes.Joint_4_Object_0_SINGLE007.geometry} material={materials['Joint_4_Object_0_Material_0.001']} skeleton={nodes.Joint_4_Object_0_SINGLE007.skeleton} />
        <skinnedMesh name="Joint_4_Object_1_SINGLE006" geometry={nodes.Joint_4_Object_1_SINGLE006.geometry} material={materials['Joint_4_Object_1_Material_1.004']} skeleton={nodes.Joint_4_Object_1_SINGLE006.skeleton} />
        <skinnedMesh name="Joint_4_Object_2_SINGLE003" geometry={nodes.Joint_4_Object_2_SINGLE003.geometry} material={materials.Joint_4_Object_2_Material_2} skeleton={nodes.Joint_4_Object_2_SINGLE003.skeleton} />
      </group>
      <group name="Armature009" position={[960, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_7} />
        <skinnedMesh name="Joint_10_Object_0_SINGLE003" geometry={nodes.Joint_10_Object_0_SINGLE003.geometry} material={materials['Joint_3_Object_0_Material_0.001']} skeleton={nodes.Joint_10_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_11_Object_0_SINGLE003" geometry={nodes.Joint_11_Object_0_SINGLE003.geometry} material={materials['Joint_4_Object_0_Material_0.001']} skeleton={nodes.Joint_11_Object_0_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_11_Object_1_SINGLE003" geometry={nodes.Joint_11_Object_1_SINGLE003.geometry} material={materials['Joint_4_Object_1_Material_1.004']} skeleton={nodes.Joint_11_Object_1_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_11_Object_2_SINGLE003" geometry={nodes.Joint_11_Object_2_SINGLE003.geometry} material={materials.Joint_4_Object_2_Material_2} skeleton={nodes.Joint_11_Object_2_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE009" geometry={nodes.Joint_2_Object_0_SINGLE009.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_2_Object_0_SINGLE009.skeleton} />
        <skinnedMesh name="Joint_2_Object_1_SINGLE004" geometry={nodes.Joint_2_Object_1_SINGLE004.geometry} material={materials.Joint_1_Object_2_Material_2} skeleton={nodes.Joint_2_Object_1_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_2_Object_2_SINGLE003" geometry={nodes.Joint_2_Object_2_SINGLE003.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_2_Object_2_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE008" geometry={nodes.Joint_3_Object_0_SINGLE008.geometry} material={materials['Joint_1_Object_0_Material_0.001']} skeleton={nodes.Joint_3_Object_0_SINGLE008.skeleton} />
        <skinnedMesh name="Joint_3_Object_1_SINGLE003" geometry={nodes.Joint_3_Object_1_SINGLE003.geometry} material={materials.Joint_1_Object_1_Material_1} skeleton={nodes.Joint_3_Object_1_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_3_Object_2_SINGLE003" geometry={nodes.Joint_3_Object_2_SINGLE003.geometry} material={materials.Joint_3_Object_2_Material_2} skeleton={nodes.Joint_3_Object_2_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_3_Object_3_SINGLE003" geometry={nodes.Joint_3_Object_3_SINGLE003.geometry} material={materials.Joint_1_Object_3_Material_3} skeleton={nodes.Joint_3_Object_3_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_3_Object_4_SINGLE003" geometry={nodes.Joint_3_Object_4_SINGLE003.geometry} material={materials.Joint_1_Object_4_Material_4} skeleton={nodes.Joint_3_Object_4_SINGLE003.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE008" geometry={nodes.Joint_4_Object_0_SINGLE008.geometry} material={materials['Joint_4_Object_0_Material_0.002']} skeleton={nodes.Joint_4_Object_0_SINGLE008.skeleton} />
        <skinnedMesh name="Joint_4_Object_1_SINGLE007" geometry={nodes.Joint_4_Object_1_SINGLE007.geometry} material={materials['Joint_4_Object_1_Material_1.001']} skeleton={nodes.Joint_4_Object_1_SINGLE007.skeleton} />
        <skinnedMesh name="Joint_5_Object_0_SINGLE004" geometry={nodes.Joint_5_Object_0_SINGLE004.geometry} material={materials['Joint_5_Object_0_Material_0.001']} skeleton={nodes.Joint_5_Object_0_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_6_Object_0_SINGLE004" geometry={nodes.Joint_6_Object_0_SINGLE004.geometry} material={materials['Joint_5_Object_0_Material_0.001']} skeleton={nodes.Joint_6_Object_0_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_7_Object_0_SINGLE004" geometry={nodes.Joint_7_Object_0_SINGLE004.geometry} material={materials['Joint_7_Object_0_Material_0.001']} skeleton={nodes.Joint_7_Object_0_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_8_Object_0_SINGLE004" geometry={nodes.Joint_8_Object_0_SINGLE004.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_8_Object_0_SINGLE004.skeleton} />
        <skinnedMesh name="Joint_9_Object_0_SINGLE004" geometry={nodes.Joint_9_Object_0_SINGLE004.geometry} material={materials['Joint_2_Object_0_Material_0.002']} skeleton={nodes.Joint_9_Object_0_SINGLE004.skeleton} />
      </group>
      <group name="Armature001" rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_8} />
        <skinnedMesh name="Joint_1_Object_0_SINGLE" geometry={nodes.Joint_1_Object_0_SINGLE.geometry} material={materials.Joint_1_Object_0_Material_0} skeleton={nodes.Joint_1_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE001" geometry={nodes.Joint_2_Object_0_SINGLE001.geometry} material={materials['Joint_2_Object_0_Material_0.001']} skeleton={nodes.Joint_2_Object_0_SINGLE001.skeleton} />
        <skinnedMesh name="Joint_3_Object_0_SINGLE" geometry={nodes.Joint_3_Object_0_SINGLE.geometry} material={materials.Joint_3_Object_0_Material_0} skeleton={nodes.Joint_3_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_4_Object_0_SINGLE" geometry={nodes.Joint_4_Object_0_SINGLE.geometry} material={materials.Joint_1_Object_0_Material_0} skeleton={nodes.Joint_4_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_5_Object_0_SINGLE" geometry={nodes.Joint_5_Object_0_SINGLE.geometry} material={materials['Joint_2_Object_0_Material_0.001']} skeleton={nodes.Joint_5_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_6_Object_0_SINGLE" geometry={nodes.Joint_6_Object_0_SINGLE.geometry} material={materials.Joint_3_Object_0_Material_0} skeleton={nodes.Joint_6_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_7_Object_0_SINGLE" geometry={nodes.Joint_7_Object_0_SINGLE.geometry} material={materials.Joint_1_Object_0_Material_0} skeleton={nodes.Joint_7_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_8_Object_0_SINGLE" geometry={nodes.Joint_8_Object_0_SINGLE.geometry} material={materials['Joint_2_Object_0_Material_0.001']} skeleton={nodes.Joint_8_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_9_Object_0_SINGLE" geometry={nodes.Joint_9_Object_0_SINGLE.geometry} material={materials.Joint_3_Object_0_Material_0} skeleton={nodes.Joint_9_Object_0_SINGLE.skeleton} />
      </group>
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.JOBJ_0_9} />
        <skinnedMesh name="Joint_2_Object_0_SINGLE" geometry={nodes.Joint_2_Object_0_SINGLE.geometry} material={materials.Joint_2_Object_0_Material_0} skeleton={nodes.Joint_2_Object_0_SINGLE.skeleton} />
        <skinnedMesh name="Joint_2_Object_1_SINGLE" geometry={nodes.Joint_2_Object_1_SINGLE.geometry} material={materials.Joint_2_Object_1_Material_1} skeleton={nodes.Joint_2_Object_1_SINGLE.skeleton} />
      </group>
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[1571.01, 0, 0]} scale={[-7479.32, -2085.32, -2085.32]} />
      <mesh name="Joint_0_Object_0" geometry={nodes.Joint_0_Object_0.geometry} material={materials.Joint_0_Object_0_Material_0} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_1" geometry={nodes.Joint_0_Object_1.geometry} material={materials['Joint_1_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_2" geometry={nodes.Joint_0_Object_2.geometry} material={materials.Joint_1_Object_1_Material_1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_3" geometry={nodes.Joint_0_Object_3.geometry} material={materials.Joint_1_Object_2_Material_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_4" geometry={nodes.Joint_0_Object_4.geometry} material={materials.Joint_1_Object_3_Material_3} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_5" geometry={nodes.Joint_0_Object_5.geometry} material={materials.Joint_1_Object_4_Material_4} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_6" geometry={nodes.Joint_0_Object_6.geometry} material={materials.Joint_1_Object_5_Material_5} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_7" geometry={nodes.Joint_0_Object_7.geometry} material={materials.Joint_1_Object_5_Material_5} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_8" geometry={nodes.Joint_0_Object_8.geometry} material={materials.Joint_1_Object_2_Material_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_9" geometry={nodes.Joint_0_Object_9.geometry} material={materials['Joint_1_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_10" geometry={nodes.Joint_0_Object_10.geometry} material={materials.Joint_1_Object_2_Material_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_11" geometry={nodes.Joint_0_Object_11.geometry} material={materials.Joint_1_Object_4_Material_4} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_12" geometry={nodes.Joint_0_Object_12.geometry} material={materials['Joint_1_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_13" geometry={nodes.Joint_0_Object_13.geometry} material={materials.Joint_1_Object_1_Material_1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_14" geometry={nodes.Joint_0_Object_14.geometry} material={materials.Joint_1_Object_2_Material_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_15" geometry={nodes.Joint_0_Object_15.geometry} material={materials.Joint_1_Object_3_Material_3} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_16" geometry={nodes.Joint_0_Object_16.geometry} material={materials.Joint_1_Object_4_Material_4} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_17" geometry={nodes.Joint_0_Object_17.geometry} material={materials['Joint_1_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_18" geometry={nodes.Joint_0_Object_18.geometry} material={materials.Joint_1_Object_1_Material_1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_19" geometry={nodes.Joint_0_Object_19.geometry} material={materials.Joint_1_Object_2_Material_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_20" geometry={nodes.Joint_0_Object_20.geometry} material={materials.Joint_1_Object_3_Material_3} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_21" geometry={nodes.Joint_0_Object_21.geometry} material={materials.Joint_1_Object_4_Material_4} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_22" geometry={nodes.Joint_0_Object_22.geometry} material={materials['Joint_1_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_23" geometry={nodes.Joint_0_Object_23.geometry} material={materials.Joint_1_Object_1_Material_1} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_24" geometry={nodes.Joint_0_Object_24.geometry} material={materials.Joint_1_Object_2_Material_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_25" geometry={nodes.Joint_0_Object_25.geometry} material={materials.Joint_1_Object_3_Material_3} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_26" geometry={nodes.Joint_0_Object_26.geometry} material={materials.Joint_1_Object_4_Material_4} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_27" geometry={nodes.Joint_0_Object_27.geometry} material={materials['Joint_5_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_28" geometry={nodes.Joint_0_Object_28.geometry} material={materials['Joint_4_Object_0_Material_0.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_29" geometry={nodes.Joint_0_Object_29.geometry} material={materials['Joint_4_Object_1_Material_1.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_30" geometry={nodes.Joint_0_Object_30.geometry} material={materials['Joint_5_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_31" geometry={nodes.Joint_0_Object_31.geometry} material={materials.Joint_0_Object_31_Material_31} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_32" geometry={nodes.Joint_0_Object_32.geometry} material={materials.Joint_0_Object_32_Material_32} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_33" geometry={nodes.Joint_0_Object_33.geometry} material={materials.Joint_0_Object_33_Material_33} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_34" geometry={nodes.Joint_0_Object_34.geometry} material={materials.Joint_0_Object_34_Material_34} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_35" geometry={nodes.Joint_0_Object_35.geometry} material={materials['Joint_4_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_36" geometry={nodes.Joint_0_Object_36.geometry} material={materials.Joint_0_Object_36_Material_36} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_37" geometry={nodes.Joint_0_Object_37.geometry} material={materials.Joint_0_Object_37_Material_37} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_38" geometry={nodes.Joint_0_Object_38.geometry} material={materials['Joint_4_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_39" geometry={nodes.Joint_0_Object_39.geometry} material={materials.Joint_4_Object_2_Material_2} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_40" geometry={nodes.Joint_0_Object_40.geometry} material={materials['Joint_7_Object_0_Material_0.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Joint_0_Object_41" geometry={nodes.Joint_0_Object_41.geometry} material={materials['Joint_2_Object_0_Material_0.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/HomeRunStadium-transformed.glb')
