/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/HyruleTemple.glb --types --keepnames --transform
*/

import * as THREE from 'three'
import React from 'react'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Joint_1_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_1_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_1_Object_2_SINGLE001: THREE.SkinnedMesh
        Joint_1_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_17_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_18_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_19_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_20_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_21_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_22_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_23_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_24_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_25_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_26_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_27_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_28_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_17_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_17_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_18_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_19_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_20_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_21_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_22_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_23_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_24_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_25_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_26_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_27_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_28_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_29_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_30_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_31_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_32_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_5_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_5_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_5_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_8_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_8_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_8_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_9_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_9_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_9_Object_2_SINGLE: THREE.SkinnedMesh
        JOBJ_0: THREE.Bone
        JOBJ_0_1: THREE.Bone
    }
    materials: {
        ['Joint_1_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        ['Joint_1_Object_1_Material_1.002']: THREE.MeshBasicMaterial
        ['Joint_1_Object_2_Material_2.001']: THREE.MeshBasicMaterial
        Joint_1_Object_3_Material_3: THREE.MeshBasicMaterial
        Joint_1_Object_4_Material_4: THREE.MeshBasicMaterial
        Joint_1_Object_5_Material_5: THREE.MeshBasicMaterial
        Joint_10_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_10_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_11_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_11_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_11_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_11_Object_3_Material_3: THREE.MeshBasicMaterial
        Joint_11_Object_5_Material_5: THREE.MeshBasicMaterial
        Joint_12_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_12_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_12_Object_3_Material_3: THREE.MeshBasicMaterial
        Joint_13_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_13_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_13_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_13_Object_4_Material_4: THREE.MeshBasicMaterial
        Joint_13_Object_5_Material_5: THREE.MeshBasicMaterial
        Joint_16_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_16_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_16_Object_6_Material_6: THREE.MeshBasicMaterial
        Joint_16_Object_9_Material_9: THREE.MeshBasicMaterial
        Joint_17_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_17_Object_10_Material_10: THREE.MeshBasicMaterial
        Joint_17_Object_11_Material_11: THREE.MeshBasicMaterial
        Joint_17_Object_12_Material_12: THREE.MeshBasicMaterial
        Joint_17_Object_13_Material_13: THREE.MeshBasicMaterial
        Joint_17_Object_14_Material_14: THREE.MeshBasicMaterial
        Joint_17_Object_15_Material_15: THREE.MeshBasicMaterial
        Joint_17_Object_18_Material_18: THREE.MeshBasicMaterial
        Joint_17_Object_19_Material_19: THREE.MeshBasicMaterial
        Joint_17_Object_22_Material_22: THREE.MeshBasicMaterial
        Joint_17_Object_25_Material_25: THREE.MeshBasicMaterial
        Joint_17_Object_26_Material_26: THREE.MeshBasicMaterial
        Joint_17_Object_27_Material_27: THREE.MeshBasicMaterial
        Joint_17_Object_28_Material_28: THREE.MeshBasicMaterial
        Joint_17_Object_5_Material_5: THREE.MeshBasicMaterial
        Joint_17_Object_6_Material_6: THREE.MeshBasicMaterial
        Joint_17_Object_7_Material_7: THREE.MeshBasicMaterial
        Joint_18_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_18_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_18_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_18_Object_3_Material_3: THREE.MeshBasicMaterial
        Joint_18_Object_4_Material_4: THREE.MeshBasicMaterial
        Joint_18_Object_5_Material_5: THREE.MeshBasicMaterial
        Joint_18_Object_6_Material_6: THREE.MeshBasicMaterial
        Joint_18_Object_7_Material_7: THREE.MeshBasicMaterial
        Joint_19_Object_11_Material_11: THREE.MeshBasicMaterial
        Joint_19_Object_13_Material_13: THREE.MeshBasicMaterial
        Joint_19_Object_14_Material_14: THREE.MeshBasicMaterial
        Joint_19_Object_4_Material_4: THREE.MeshBasicMaterial
        Joint_19_Object_6_Material_6: THREE.MeshBasicMaterial
        Joint_19_Object_8_Material_8: THREE.MeshBasicMaterial
        Joint_21_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_21_Object_14_Material_14: THREE.MeshBasicMaterial
        Joint_21_Object_3_Material_3: THREE.MeshBasicMaterial
        Joint_22_Object_10_Material_10: THREE.MeshBasicMaterial
        Joint_22_Object_12_Material_12: THREE.MeshBasicMaterial
        Joint_22_Object_13_Material_13: THREE.MeshBasicMaterial
        Joint_22_Object_4_Material_4: THREE.MeshBasicMaterial
        Joint_2_Object_10_Material_10: THREE.MeshBasicMaterial
        Joint_2_Object_12_Material_12: THREE.MeshBasicMaterial
        Joint_2_Object_13_Material_13: THREE.MeshBasicMaterial
        Joint_2_Object_14_Material_14: THREE.MeshBasicMaterial
        Joint_2_Object_15_Material_15: THREE.MeshBasicMaterial
        Joint_3_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_5_Object_2_Material_2: THREE.MeshBasicMaterial
    }
}

export default function HyruleTemple(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/HyruleTemple-transformed.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group name="Armature001" rotation={[Math.PI / 2, 0, 0]}>
                <primitive object={nodes.JOBJ_0}/>
                <skinnedMesh name="Joint_1_Object_0_SINGLE001" geometry={nodes.Joint_1_Object_0_SINGLE001.geometry}
                             material={materials['Joint_1_Object_0_Material_0.001']}
                             skeleton={nodes.Joint_1_Object_0_SINGLE001.skeleton}/>
                <skinnedMesh name="Joint_1_Object_1_SINGLE001" geometry={nodes.Joint_1_Object_1_SINGLE001.geometry}
                             material={materials['Joint_1_Object_1_Material_1.002']}
                             skeleton={nodes.Joint_1_Object_1_SINGLE001.skeleton}/>
                <skinnedMesh name="Joint_1_Object_2_SINGLE001" geometry={nodes.Joint_1_Object_2_SINGLE001.geometry}
                             material={materials['Joint_1_Object_2_Material_2.001']}
                             skeleton={nodes.Joint_1_Object_2_SINGLE001.skeleton}/>
                <skinnedMesh name="Joint_1_Object_3_SINGLE" geometry={nodes.Joint_1_Object_3_SINGLE.geometry}
                             material={materials.Joint_1_Object_3_Material_3}
                             skeleton={nodes.Joint_1_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_1_Object_4_SINGLE" geometry={nodes.Joint_1_Object_4_SINGLE.geometry}
                             material={materials.Joint_1_Object_4_Material_4}
                             skeleton={nodes.Joint_1_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_1_Object_5_SINGLE" geometry={nodes.Joint_1_Object_5_SINGLE.geometry}
                             material={materials.Joint_1_Object_5_Material_5}
                             skeleton={nodes.Joint_1_Object_5_SINGLE.skeleton}/>
            </group>
            <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
                <primitive object={nodes.JOBJ_0_1}/>
                <skinnedMesh name="Joint_10_Object_0_SINGLE" geometry={nodes.Joint_10_Object_0_SINGLE.geometry}
                             material={materials.Joint_10_Object_0_Material_0}
                             skeleton={nodes.Joint_10_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_10_Object_1_SINGLE" geometry={nodes.Joint_10_Object_1_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_10_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_10_Object_2_SINGLE" geometry={nodes.Joint_10_Object_2_SINGLE.geometry}
                             material={materials.Joint_10_Object_0_Material_0}
                             skeleton={nodes.Joint_10_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_11_Object_0_SINGLE" geometry={nodes.Joint_11_Object_0_SINGLE.geometry}
                             material={materials.Joint_11_Object_0_Material_0}
                             skeleton={nodes.Joint_11_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_11_Object_1_SINGLE" geometry={nodes.Joint_11_Object_1_SINGLE.geometry}
                             material={materials.Joint_11_Object_1_Material_1}
                             skeleton={nodes.Joint_11_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_11_Object_2_SINGLE" geometry={nodes.Joint_11_Object_2_SINGLE.geometry}
                             material={materials.Joint_11_Object_2_Material_2}
                             skeleton={nodes.Joint_11_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_11_Object_3_SINGLE" geometry={nodes.Joint_11_Object_3_SINGLE.geometry}
                             material={materials.Joint_11_Object_3_Material_3}
                             skeleton={nodes.Joint_11_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_11_Object_4_SINGLE" geometry={nodes.Joint_11_Object_4_SINGLE.geometry}
                             material={materials.Joint_11_Object_0_Material_0}
                             skeleton={nodes.Joint_11_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_11_Object_5_SINGLE" geometry={nodes.Joint_11_Object_5_SINGLE.geometry}
                             material={materials.Joint_11_Object_5_Material_5}
                             skeleton={nodes.Joint_11_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_11_Object_6_SINGLE" geometry={nodes.Joint_11_Object_6_SINGLE.geometry}
                             material={materials.Joint_10_Object_0_Material_0}
                             skeleton={nodes.Joint_11_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_11_Object_7_SINGLE" geometry={nodes.Joint_11_Object_7_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_11_Object_7_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_12_Object_0_SINGLE" geometry={nodes.Joint_12_Object_0_SINGLE.geometry}
                             material={materials.Joint_12_Object_0_Material_0}
                             skeleton={nodes.Joint_12_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_12_Object_1_SINGLE" geometry={nodes.Joint_12_Object_1_SINGLE.geometry}
                             material={materials.Joint_12_Object_0_Material_0}
                             skeleton={nodes.Joint_12_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_12_Object_2_SINGLE" geometry={nodes.Joint_12_Object_2_SINGLE.geometry}
                             material={materials.Joint_12_Object_2_Material_2}
                             skeleton={nodes.Joint_12_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_12_Object_3_SINGLE" geometry={nodes.Joint_12_Object_3_SINGLE.geometry}
                             material={materials.Joint_12_Object_3_Material_3}
                             skeleton={nodes.Joint_12_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_12_Object_4_SINGLE" geometry={nodes.Joint_12_Object_4_SINGLE.geometry}
                             material={materials.Joint_12_Object_3_Material_3}
                             skeleton={nodes.Joint_12_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_13_Object_0_SINGLE" geometry={nodes.Joint_13_Object_0_SINGLE.geometry}
                             material={materials.Joint_13_Object_0_Material_0}
                             skeleton={nodes.Joint_13_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_13_Object_1_SINGLE" geometry={nodes.Joint_13_Object_1_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_13_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_13_Object_2_SINGLE" geometry={nodes.Joint_13_Object_2_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_13_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_13_Object_3_SINGLE" geometry={nodes.Joint_13_Object_3_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_13_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_13_Object_4_SINGLE" geometry={nodes.Joint_13_Object_4_SINGLE.geometry}
                             material={materials.Joint_13_Object_4_Material_4}
                             skeleton={nodes.Joint_13_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_13_Object_5_SINGLE" geometry={nodes.Joint_13_Object_5_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_13_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_14_Object_0_SINGLE" geometry={nodes.Joint_14_Object_0_SINGLE.geometry}
                             material={materials.Joint_12_Object_2_Material_2}
                             skeleton={nodes.Joint_14_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_14_Object_1_SINGLE" geometry={nodes.Joint_14_Object_1_SINGLE.geometry}
                             material={materials.Joint_12_Object_3_Material_3}
                             skeleton={nodes.Joint_14_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_14_Object_2_SINGLE" geometry={nodes.Joint_14_Object_2_SINGLE.geometry}
                             material={materials.Joint_12_Object_3_Material_3}
                             skeleton={nodes.Joint_14_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_15_Object_0_SINGLE" geometry={nodes.Joint_15_Object_0_SINGLE.geometry}
                             material={materials.Joint_12_Object_2_Material_2}
                             skeleton={nodes.Joint_15_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_15_Object_1_SINGLE" geometry={nodes.Joint_15_Object_1_SINGLE.geometry}
                             material={materials.Joint_12_Object_3_Material_3}
                             skeleton={nodes.Joint_15_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_15_Object_2_SINGLE" geometry={nodes.Joint_15_Object_2_SINGLE.geometry}
                             material={materials.Joint_12_Object_3_Material_3}
                             skeleton={nodes.Joint_15_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_15_Object_3_SINGLE" geometry={nodes.Joint_15_Object_3_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_15_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_15_Object_4_SINGLE" geometry={nodes.Joint_15_Object_4_SINGLE.geometry}
                             material={materials.Joint_13_Object_4_Material_4}
                             skeleton={nodes.Joint_15_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_15_Object_5_SINGLE" geometry={nodes.Joint_15_Object_5_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_15_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_0_SINGLE" geometry={nodes.Joint_16_Object_0_SINGLE.geometry}
                             material={materials.Joint_11_Object_0_Material_0}
                             skeleton={nodes.Joint_16_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_10_SINGLE" geometry={nodes.Joint_16_Object_10_SINGLE.geometry}
                             material={materials.Joint_11_Object_0_Material_0}
                             skeleton={nodes.Joint_16_Object_10_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_1_SINGLE" geometry={nodes.Joint_16_Object_1_SINGLE.geometry}
                             material={materials.Joint_16_Object_1_Material_1}
                             skeleton={nodes.Joint_16_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_2_SINGLE" geometry={nodes.Joint_16_Object_2_SINGLE.geometry}
                             material={materials.Joint_16_Object_2_Material_2}
                             skeleton={nodes.Joint_16_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_3_SINGLE" geometry={nodes.Joint_16_Object_3_SINGLE.geometry}
                             material={materials.Joint_16_Object_1_Material_1}
                             skeleton={nodes.Joint_16_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_4_SINGLE" geometry={nodes.Joint_16_Object_4_SINGLE.geometry}
                             material={materials.Joint_16_Object_2_Material_2}
                             skeleton={nodes.Joint_16_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_5_SINGLE" geometry={nodes.Joint_16_Object_5_SINGLE.geometry}
                             material={materials.Joint_16_Object_1_Material_1}
                             skeleton={nodes.Joint_16_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_6_SINGLE" geometry={nodes.Joint_16_Object_6_SINGLE.geometry}
                             material={materials.Joint_16_Object_6_Material_6}
                             skeleton={nodes.Joint_16_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_7_SINGLE" geometry={nodes.Joint_16_Object_7_SINGLE.geometry}
                             material={materials.Joint_11_Object_3_Material_3}
                             skeleton={nodes.Joint_16_Object_7_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_8_SINGLE" geometry={nodes.Joint_16_Object_8_SINGLE.geometry}
                             material={materials.Joint_11_Object_0_Material_0}
                             skeleton={nodes.Joint_16_Object_8_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_16_Object_9_SINGLE" geometry={nodes.Joint_16_Object_9_SINGLE.geometry}
                             material={materials.Joint_16_Object_9_Material_9}
                             skeleton={nodes.Joint_16_Object_9_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_0_SINGLE" geometry={nodes.Joint_17_Object_0_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_17_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_10_SINGLE" geometry={nodes.Joint_17_Object_10_SINGLE.geometry}
                             material={materials.Joint_17_Object_10_Material_10}
                             skeleton={nodes.Joint_17_Object_10_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_11_SINGLE" geometry={nodes.Joint_17_Object_11_SINGLE.geometry}
                             material={materials.Joint_17_Object_11_Material_11}
                             skeleton={nodes.Joint_17_Object_11_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_12_SINGLE" geometry={nodes.Joint_17_Object_12_SINGLE.geometry}
                             material={materials.Joint_17_Object_12_Material_12}
                             skeleton={nodes.Joint_17_Object_12_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_13_SINGLE" geometry={nodes.Joint_17_Object_13_SINGLE.geometry}
                             material={materials.Joint_17_Object_13_Material_13}
                             skeleton={nodes.Joint_17_Object_13_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_14_SINGLE" geometry={nodes.Joint_17_Object_14_SINGLE.geometry}
                             material={materials.Joint_17_Object_14_Material_14}
                             skeleton={nodes.Joint_17_Object_14_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_15_SINGLE" geometry={nodes.Joint_17_Object_15_SINGLE.geometry}
                             material={materials.Joint_17_Object_15_Material_15}
                             skeleton={nodes.Joint_17_Object_15_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_16_SINGLE" geometry={nodes.Joint_17_Object_16_SINGLE.geometry}
                             material={materials.Joint_17_Object_13_Material_13}
                             skeleton={nodes.Joint_17_Object_16_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_17_SINGLE" geometry={nodes.Joint_17_Object_17_SINGLE.geometry}
                             material={materials.Joint_17_Object_14_Material_14}
                             skeleton={nodes.Joint_17_Object_17_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_18_SINGLE" geometry={nodes.Joint_17_Object_18_SINGLE.geometry}
                             material={materials.Joint_17_Object_18_Material_18}
                             skeleton={nodes.Joint_17_Object_18_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_19_SINGLE" geometry={nodes.Joint_17_Object_19_SINGLE.geometry}
                             material={materials.Joint_17_Object_19_Material_19}
                             skeleton={nodes.Joint_17_Object_19_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_1_SINGLE" geometry={nodes.Joint_17_Object_1_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_17_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_20_SINGLE" geometry={nodes.Joint_17_Object_20_SINGLE.geometry}
                             material={materials.Joint_17_Object_13_Material_13}
                             skeleton={nodes.Joint_17_Object_20_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_21_SINGLE" geometry={nodes.Joint_17_Object_21_SINGLE.geometry}
                             material={materials.Joint_17_Object_13_Material_13}
                             skeleton={nodes.Joint_17_Object_21_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_22_SINGLE" geometry={nodes.Joint_17_Object_22_SINGLE.geometry}
                             material={materials.Joint_17_Object_22_Material_22}
                             skeleton={nodes.Joint_17_Object_22_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_23_SINGLE" geometry={nodes.Joint_17_Object_23_SINGLE.geometry}
                             material={materials.Joint_17_Object_13_Material_13}
                             skeleton={nodes.Joint_17_Object_23_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_24_SINGLE" geometry={nodes.Joint_17_Object_24_SINGLE.geometry}
                             material={materials.Joint_17_Object_18_Material_18}
                             skeleton={nodes.Joint_17_Object_24_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_25_SINGLE" geometry={nodes.Joint_17_Object_25_SINGLE.geometry}
                             material={materials.Joint_17_Object_25_Material_25}
                             skeleton={nodes.Joint_17_Object_25_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_26_SINGLE" geometry={nodes.Joint_17_Object_26_SINGLE.geometry}
                             material={materials.Joint_17_Object_26_Material_26}
                             skeleton={nodes.Joint_17_Object_26_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_27_SINGLE" geometry={nodes.Joint_17_Object_27_SINGLE.geometry}
                             material={materials.Joint_17_Object_27_Material_27}
                             skeleton={nodes.Joint_17_Object_27_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_28_SINGLE" geometry={nodes.Joint_17_Object_28_SINGLE.geometry}
                             material={materials.Joint_17_Object_28_Material_28}
                             skeleton={nodes.Joint_17_Object_28_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_2_SINGLE" geometry={nodes.Joint_17_Object_2_SINGLE.geometry}
                             material={materials.Joint_17_Object_14_Material_14}
                             skeleton={nodes.Joint_17_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_3_SINGLE" geometry={nodes.Joint_17_Object_3_SINGLE.geometry}
                             material={materials.Joint_17_Object_15_Material_15}
                             skeleton={nodes.Joint_17_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_4_SINGLE" geometry={nodes.Joint_17_Object_4_SINGLE.geometry}
                             material={materials.Joint_17_Object_13_Material_13}
                             skeleton={nodes.Joint_17_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_5_SINGLE" geometry={nodes.Joint_17_Object_5_SINGLE.geometry}
                             material={materials.Joint_17_Object_5_Material_5}
                             skeleton={nodes.Joint_17_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_6_SINGLE" geometry={nodes.Joint_17_Object_6_SINGLE.geometry}
                             material={materials.Joint_17_Object_6_Material_6}
                             skeleton={nodes.Joint_17_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_7_SINGLE" geometry={nodes.Joint_17_Object_7_SINGLE.geometry}
                             material={materials.Joint_17_Object_7_Material_7}
                             skeleton={nodes.Joint_17_Object_7_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_8_SINGLE" geometry={nodes.Joint_17_Object_8_SINGLE.geometry}
                             material={materials.Joint_17_Object_14_Material_14}
                             skeleton={nodes.Joint_17_Object_8_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_17_Object_9_SINGLE" geometry={nodes.Joint_17_Object_9_SINGLE.geometry}
                             material={materials.Joint_17_Object_15_Material_15}
                             skeleton={nodes.Joint_17_Object_9_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_18_Object_0_SINGLE" geometry={nodes.Joint_18_Object_0_SINGLE.geometry}
                             material={materials.Joint_18_Object_0_Material_0}
                             skeleton={nodes.Joint_18_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_18_Object_1_SINGLE" geometry={nodes.Joint_18_Object_1_SINGLE.geometry}
                             material={materials.Joint_18_Object_1_Material_1}
                             skeleton={nodes.Joint_18_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_18_Object_2_SINGLE" geometry={nodes.Joint_18_Object_2_SINGLE.geometry}
                             material={materials.Joint_18_Object_2_Material_2}
                             skeleton={nodes.Joint_18_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_18_Object_3_SINGLE" geometry={nodes.Joint_18_Object_3_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_18_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_18_Object_4_SINGLE" geometry={nodes.Joint_18_Object_4_SINGLE.geometry}
                             material={materials.Joint_18_Object_4_Material_4}
                             skeleton={nodes.Joint_18_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_18_Object_5_SINGLE" geometry={nodes.Joint_18_Object_5_SINGLE.geometry}
                             material={materials.Joint_18_Object_5_Material_5}
                             skeleton={nodes.Joint_18_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_18_Object_6_SINGLE" geometry={nodes.Joint_18_Object_6_SINGLE.geometry}
                             material={materials.Joint_18_Object_6_Material_6}
                             skeleton={nodes.Joint_18_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_18_Object_7_SINGLE" geometry={nodes.Joint_18_Object_7_SINGLE.geometry}
                             material={materials.Joint_18_Object_7_Material_7}
                             skeleton={nodes.Joint_18_Object_7_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_0_SINGLE" geometry={nodes.Joint_19_Object_0_SINGLE.geometry}
                             material={materials.Joint_18_Object_2_Material_2}
                             skeleton={nodes.Joint_19_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_10_SINGLE" geometry={nodes.Joint_19_Object_10_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_19_Object_10_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_11_SINGLE" geometry={nodes.Joint_19_Object_11_SINGLE.geometry}
                             material={materials.Joint_19_Object_11_Material_11}
                             skeleton={nodes.Joint_19_Object_11_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_12_SINGLE" geometry={nodes.Joint_19_Object_12_SINGLE.geometry}
                             material={materials.Joint_19_Object_11_Material_11}
                             skeleton={nodes.Joint_19_Object_12_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_13_SINGLE" geometry={nodes.Joint_19_Object_13_SINGLE.geometry}
                             material={materials.Joint_19_Object_13_Material_13}
                             skeleton={nodes.Joint_19_Object_13_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_14_SINGLE" geometry={nodes.Joint_19_Object_14_SINGLE.geometry}
                             material={materials.Joint_19_Object_14_Material_14}
                             skeleton={nodes.Joint_19_Object_14_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_15_SINGLE" geometry={nodes.Joint_19_Object_15_SINGLE.geometry}
                             material={materials.Joint_19_Object_11_Material_11}
                             skeleton={nodes.Joint_19_Object_15_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_16_SINGLE" geometry={nodes.Joint_19_Object_16_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_19_Object_16_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_17_SINGLE" geometry={nodes.Joint_19_Object_17_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_19_Object_17_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_1_SINGLE" geometry={nodes.Joint_19_Object_1_SINGLE.geometry}
                             material={materials.Joint_18_Object_2_Material_2}
                             skeleton={nodes.Joint_19_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_2_SINGLE" geometry={nodes.Joint_19_Object_2_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_19_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_3_SINGLE" geometry={nodes.Joint_19_Object_3_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_19_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_4_SINGLE" geometry={nodes.Joint_19_Object_4_SINGLE.geometry}
                             material={materials.Joint_19_Object_4_Material_4}
                             skeleton={nodes.Joint_19_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_5_SINGLE" geometry={nodes.Joint_19_Object_5_SINGLE.geometry}
                             material={materials.Joint_19_Object_4_Material_4}
                             skeleton={nodes.Joint_19_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_6_SINGLE" geometry={nodes.Joint_19_Object_6_SINGLE.geometry}
                             material={materials.Joint_19_Object_6_Material_6}
                             skeleton={nodes.Joint_19_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_7_SINGLE" geometry={nodes.Joint_19_Object_7_SINGLE.geometry}
                             material={materials.Joint_19_Object_4_Material_4}
                             skeleton={nodes.Joint_19_Object_7_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_8_SINGLE" geometry={nodes.Joint_19_Object_8_SINGLE.geometry}
                             material={materials.Joint_19_Object_8_Material_8}
                             skeleton={nodes.Joint_19_Object_8_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_19_Object_9_SINGLE" geometry={nodes.Joint_19_Object_9_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_19_Object_9_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_1_Object_0_SINGLE" geometry={nodes.Joint_1_Object_0_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_1_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_1_Object_1_SINGLE" geometry={nodes.Joint_1_Object_1_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_1_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_1_Object_2_SINGLE" geometry={nodes.Joint_1_Object_2_SINGLE.geometry}
                             material={materials.Joint_16_Object_9_Material_9}
                             skeleton={nodes.Joint_1_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_0_SINGLE" geometry={nodes.Joint_21_Object_0_SINGLE.geometry}
                             material={materials.Joint_21_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_10_SINGLE" geometry={nodes.Joint_21_Object_10_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_10_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_11_SINGLE" geometry={nodes.Joint_21_Object_11_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_11_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_12_SINGLE" geometry={nodes.Joint_21_Object_12_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_12_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_13_SINGLE" geometry={nodes.Joint_21_Object_13_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_13_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_14_SINGLE" geometry={nodes.Joint_21_Object_14_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_14_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_15_SINGLE" geometry={nodes.Joint_21_Object_15_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_15_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_16_SINGLE" geometry={nodes.Joint_21_Object_16_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_16_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_17_SINGLE" geometry={nodes.Joint_21_Object_17_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_17_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_18_SINGLE" geometry={nodes.Joint_21_Object_18_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_18_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_19_SINGLE" geometry={nodes.Joint_21_Object_19_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_19_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_1_SINGLE" geometry={nodes.Joint_21_Object_1_SINGLE.geometry}
                             material={materials.Joint_21_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_20_SINGLE" geometry={nodes.Joint_21_Object_20_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_20_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_21_SINGLE" geometry={nodes.Joint_21_Object_21_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_21_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_22_SINGLE" geometry={nodes.Joint_21_Object_22_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_22_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_23_SINGLE" geometry={nodes.Joint_21_Object_23_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_23_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_24_SINGLE" geometry={nodes.Joint_21_Object_24_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_24_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_25_SINGLE" geometry={nodes.Joint_21_Object_25_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_25_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_26_SINGLE" geometry={nodes.Joint_21_Object_26_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_26_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_27_SINGLE" geometry={nodes.Joint_21_Object_27_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_27_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_28_SINGLE" geometry={nodes.Joint_21_Object_28_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_28_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_29_SINGLE" geometry={nodes.Joint_21_Object_29_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_29_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_2_SINGLE" geometry={nodes.Joint_21_Object_2_SINGLE.geometry}
                             material={materials.Joint_21_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_30_SINGLE" geometry={nodes.Joint_21_Object_30_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_30_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_31_SINGLE" geometry={nodes.Joint_21_Object_31_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_21_Object_31_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_32_SINGLE" geometry={nodes.Joint_21_Object_32_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_21_Object_32_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_3_SINGLE" geometry={nodes.Joint_21_Object_3_SINGLE.geometry}
                             material={materials.Joint_21_Object_3_Material_3}
                             skeleton={nodes.Joint_21_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_4_SINGLE" geometry={nodes.Joint_21_Object_4_SINGLE.geometry}
                             material={materials.Joint_21_Object_3_Material_3}
                             skeleton={nodes.Joint_21_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_5_SINGLE" geometry={nodes.Joint_21_Object_5_SINGLE.geometry}
                             material={materials.Joint_21_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_6_SINGLE" geometry={nodes.Joint_21_Object_6_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_21_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_7_SINGLE" geometry={nodes.Joint_21_Object_7_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_7_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_8_SINGLE" geometry={nodes.Joint_21_Object_8_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_21_Object_8_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_21_Object_9_SINGLE" geometry={nodes.Joint_21_Object_9_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_21_Object_9_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_0_SINGLE" geometry={nodes.Joint_22_Object_0_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_22_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_10_SINGLE" geometry={nodes.Joint_22_Object_10_SINGLE.geometry}
                             material={materials.Joint_22_Object_10_Material_10}
                             skeleton={nodes.Joint_22_Object_10_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_11_SINGLE" geometry={nodes.Joint_22_Object_11_SINGLE.geometry}
                             material={materials.Joint_17_Object_7_Material_7}
                             skeleton={nodes.Joint_22_Object_11_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_12_SINGLE" geometry={nodes.Joint_22_Object_12_SINGLE.geometry}
                             material={materials.Joint_22_Object_12_Material_12}
                             skeleton={nodes.Joint_22_Object_12_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_13_SINGLE" geometry={nodes.Joint_22_Object_13_SINGLE.geometry}
                             material={materials.Joint_22_Object_13_Material_13}
                             skeleton={nodes.Joint_22_Object_13_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_1_SINGLE" geometry={nodes.Joint_22_Object_1_SINGLE.geometry}
                             material={materials.Joint_12_Object_2_Material_2}
                             skeleton={nodes.Joint_22_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_2_SINGLE" geometry={nodes.Joint_22_Object_2_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_22_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_3_SINGLE" geometry={nodes.Joint_22_Object_3_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_22_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_4_SINGLE" geometry={nodes.Joint_22_Object_4_SINGLE.geometry}
                             material={materials.Joint_22_Object_4_Material_4}
                             skeleton={nodes.Joint_22_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_5_SINGLE" geometry={nodes.Joint_22_Object_5_SINGLE.geometry}
                             material={materials.Joint_22_Object_4_Material_4}
                             skeleton={nodes.Joint_22_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_6_SINGLE" geometry={nodes.Joint_22_Object_6_SINGLE.geometry}
                             material={materials.Joint_17_Object_0_Material_0}
                             skeleton={nodes.Joint_22_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_7_SINGLE" geometry={nodes.Joint_22_Object_7_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_22_Object_7_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_8_SINGLE" geometry={nodes.Joint_22_Object_8_SINGLE.geometry}
                             material={materials.Joint_18_Object_3_Material_3}
                             skeleton={nodes.Joint_22_Object_8_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_22_Object_9_SINGLE" geometry={nodes.Joint_22_Object_9_SINGLE.geometry}
                             material={materials.Joint_12_Object_3_Material_3}
                             skeleton={nodes.Joint_22_Object_9_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_0_SINGLE" geometry={nodes.Joint_2_Object_0_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_2_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_10_SINGLE" geometry={nodes.Joint_2_Object_10_SINGLE.geometry}
                             material={materials.Joint_2_Object_10_Material_10}
                             skeleton={nodes.Joint_2_Object_10_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_11_SINGLE" geometry={nodes.Joint_2_Object_11_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_2_Object_11_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_12_SINGLE" geometry={nodes.Joint_2_Object_12_SINGLE.geometry}
                             material={materials.Joint_2_Object_12_Material_12}
                             skeleton={nodes.Joint_2_Object_12_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_13_SINGLE" geometry={nodes.Joint_2_Object_13_SINGLE.geometry}
                             material={materials.Joint_2_Object_13_Material_13}
                             skeleton={nodes.Joint_2_Object_13_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_14_SINGLE" geometry={nodes.Joint_2_Object_14_SINGLE.geometry}
                             material={materials.Joint_2_Object_14_Material_14}
                             skeleton={nodes.Joint_2_Object_14_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_15_SINGLE" geometry={nodes.Joint_2_Object_15_SINGLE.geometry}
                             material={materials.Joint_2_Object_15_Material_15}
                             skeleton={nodes.Joint_2_Object_15_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_1_SINGLE" geometry={nodes.Joint_2_Object_1_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_2_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_2_SINGLE" geometry={nodes.Joint_2_Object_2_SINGLE.geometry}
                             material={materials.Joint_13_Object_4_Material_4}
                             skeleton={nodes.Joint_2_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_3_SINGLE" geometry={nodes.Joint_2_Object_3_SINGLE.geometry}
                             material={materials.Joint_13_Object_4_Material_4}
                             skeleton={nodes.Joint_2_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_4_SINGLE" geometry={nodes.Joint_2_Object_4_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_2_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_5_SINGLE" geometry={nodes.Joint_2_Object_5_SINGLE.geometry}
                             material={materials.Joint_13_Object_4_Material_4}
                             skeleton={nodes.Joint_2_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_6_SINGLE" geometry={nodes.Joint_2_Object_6_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_2_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_7_SINGLE" geometry={nodes.Joint_2_Object_7_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_2_Object_7_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_8_SINGLE" geometry={nodes.Joint_2_Object_8_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_2_Object_8_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_2_Object_9_SINGLE" geometry={nodes.Joint_2_Object_9_SINGLE.geometry}
                             material={materials.Joint_13_Object_4_Material_4}
                             skeleton={nodes.Joint_2_Object_9_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_3_Object_0_SINGLE" geometry={nodes.Joint_3_Object_0_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_3_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_3_Object_1_SINGLE" geometry={nodes.Joint_3_Object_1_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_3_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_3_Object_2_SINGLE" geometry={nodes.Joint_3_Object_2_SINGLE.geometry}
                             material={materials.Joint_3_Object_2_Material_2}
                             skeleton={nodes.Joint_3_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_4_Object_0_SINGLE" geometry={nodes.Joint_4_Object_0_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_4_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_4_Object_1_SINGLE" geometry={nodes.Joint_4_Object_1_SINGLE.geometry}
                             material={materials.Joint_13_Object_2_Material_2}
                             skeleton={nodes.Joint_4_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_4_Object_2_SINGLE" geometry={nodes.Joint_4_Object_2_SINGLE.geometry}
                             material={materials.Joint_21_Object_14_Material_14}
                             skeleton={nodes.Joint_4_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_4_Object_3_SINGLE" geometry={nodes.Joint_4_Object_3_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_4_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_4_Object_4_SINGLE" geometry={nodes.Joint_4_Object_4_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_4_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_4_Object_5_SINGLE" geometry={nodes.Joint_4_Object_5_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_4_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_4_Object_6_SINGLE" geometry={nodes.Joint_4_Object_6_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_4_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_5_Object_0_SINGLE" geometry={nodes.Joint_5_Object_0_SINGLE.geometry}
                             material={materials.Joint_11_Object_2_Material_2}
                             skeleton={nodes.Joint_5_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_5_Object_1_SINGLE" geometry={nodes.Joint_5_Object_1_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_5_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_5_Object_2_SINGLE" geometry={nodes.Joint_5_Object_2_SINGLE.geometry}
                             material={materials.Joint_5_Object_2_Material_2}
                             skeleton={nodes.Joint_5_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_6_Object_0_SINGLE" geometry={nodes.Joint_6_Object_0_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_6_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_6_Object_1_SINGLE" geometry={nodes.Joint_6_Object_1_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_6_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_6_Object_2_SINGLE" geometry={nodes.Joint_6_Object_2_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_6_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_6_Object_3_SINGLE" geometry={nodes.Joint_6_Object_3_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_6_Object_3_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_6_Object_4_SINGLE" geometry={nodes.Joint_6_Object_4_SINGLE.geometry}
                             material={materials.Joint_13_Object_5_Material_5}
                             skeleton={nodes.Joint_6_Object_4_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_6_Object_5_SINGLE" geometry={nodes.Joint_6_Object_5_SINGLE.geometry}
                             material={materials.Joint_13_Object_1_Material_1}
                             skeleton={nodes.Joint_6_Object_5_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_6_Object_6_SINGLE" geometry={nodes.Joint_6_Object_6_SINGLE.geometry}
                             material={materials.Joint_16_Object_9_Material_9}
                             skeleton={nodes.Joint_6_Object_6_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_7_Object_0_SINGLE" geometry={nodes.Joint_7_Object_0_SINGLE.geometry}
                             material={materials.Joint_11_Object_2_Material_2}
                             skeleton={nodes.Joint_7_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_7_Object_1_SINGLE" geometry={nodes.Joint_7_Object_1_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_7_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_7_Object_2_SINGLE" geometry={nodes.Joint_7_Object_2_SINGLE.geometry}
                             material={materials.Joint_5_Object_2_Material_2}
                             skeleton={nodes.Joint_7_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_8_Object_0_SINGLE" geometry={nodes.Joint_8_Object_0_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_8_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_8_Object_1_SINGLE" geometry={nodes.Joint_8_Object_1_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_8_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_8_Object_2_SINGLE" geometry={nodes.Joint_8_Object_2_SINGLE.geometry}
                             material={materials.Joint_5_Object_2_Material_2}
                             skeleton={nodes.Joint_8_Object_2_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_9_Object_0_SINGLE" geometry={nodes.Joint_9_Object_0_SINGLE.geometry}
                             material={materials.Joint_10_Object_0_Material_0}
                             skeleton={nodes.Joint_9_Object_0_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_9_Object_1_SINGLE" geometry={nodes.Joint_9_Object_1_SINGLE.geometry}
                             material={materials.Joint_10_Object_1_Material_1}
                             skeleton={nodes.Joint_9_Object_1_SINGLE.skeleton}/>
                <skinnedMesh name="Joint_9_Object_2_SINGLE" geometry={nodes.Joint_9_Object_2_SINGLE.geometry}
                             material={materials.Joint_10_Object_0_Material_0}
                             skeleton={nodes.Joint_9_Object_2_SINGLE.skeleton}/>
            </group>
        </group>
    )
}

useGLTF.preload('/HyruleTemple-transformed.glb')
