/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/YS_Render.glb --types --keepnames --transform
*/

import * as THREE from 'three'
import {AnimationClip} from 'three'
import React, {useEffect, useRef} from 'react'
import {useAnimations, useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'

type ActionName = 'new_anim.001' | 'model_skeletonAction' | 'new_anim' | 'ArmatureAction'

interface GLTFAction extends AnimationClip {
    name: ActionName;
}

type GLTFResult = GLTF & {
    nodes: {
        Joint_10_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_10_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_11_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_12_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_12_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_13_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_13_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_14_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_14_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_15_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_15_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_16_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_16_Object_2_SINGLE001: THREE.SkinnedMesh
        Joint_17_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_17_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_17_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_18_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_18_Object_2_SINGLE001: THREE.SkinnedMesh
        Joint_18_Object_3_SINGLE001: THREE.SkinnedMesh
        Joint_19_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_19_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_19_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_0_SINGLE002: THREE.SkinnedMesh
        Joint_1_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_1_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_3_SINGLE001: THREE.SkinnedMesh
        Joint_20_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_20_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_20_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_20_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_21_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_22_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_23_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_23_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_23_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_23_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_24_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_24_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_24_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_24_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_2_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_2_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_3_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_3_Object_2_SINGLE001: THREE.SkinnedMesh
        Joint_3_Object_3_SINGLE001: THREE.SkinnedMesh
        Joint_4_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_4_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_4_Object_2_SINGLE001: THREE.SkinnedMesh
        Joint_4_Object_3_SINGLE001: THREE.SkinnedMesh
        Joint_5_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_5_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_5_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_5_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_6_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_6_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_0_SINGLE001: THREE.SkinnedMesh
        Joint_7_Object_1_SINGLE001: THREE.SkinnedMesh
        Joint_7_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_8_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_8_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_8_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_9_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_9_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_9_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_9_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_12_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_13_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_14_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_15_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_16_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_17_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_18_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_19_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_20_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_20_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_2_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_17_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_18_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_19_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_20_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_21_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_22_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_23_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_24_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_25_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_3_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_10_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_11_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_12_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_13_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_14_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_15_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_16_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_17_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_18_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_19_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_2_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_3_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_4_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_5_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_6_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_7_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_8_SINGLE: THREE.SkinnedMesh
        Joint_4_Object_9_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_6_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_0_SINGLE: THREE.SkinnedMesh
        Joint_7_Object_1_SINGLE: THREE.SkinnedMesh
        Joint_1_Object_0_SINGLE001: THREE.SkinnedMesh
        Cube: THREE.Mesh
        particle: THREE.Mesh
        JOBJ_0: THREE.Bone
        JOBJ_0_1: THREE.Bone
        JOBJ_0_2: THREE.Bone
        JOBJ_0_3: THREE.Bone
    }
    materials: {
        Joint_10_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_10_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_10_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_10_Object_3_Material_3: THREE.MeshStandardMaterial
        Joint_11_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_11_Object_2_Material_2: THREE.MeshBasicMaterial
        ['Joint_12_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        ['Joint_14_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        Joint_11_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_1_Object_2_Material_2: THREE.MeshBasicMaterial
        ['Joint_1_Object_3_Material_3.001']: THREE.MeshBasicMaterial
        Joint_20_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_24_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_24_Object_3_Material_3: THREE.MeshStandardMaterial
        Joint_9_Object_2_Material_2: THREE.MeshBasicMaterial
        Joint_12_Object_0_Material_0: THREE.MeshStandardMaterial
        Joint_12_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_13_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_14_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_15_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_16_Object_0_Material_0: THREE.MeshStandardMaterial
        Joint_16_Object_11_Material_11: THREE.MeshBasicMaterial
        Joint_16_Object_15_Material_15: THREE.MeshBasicMaterial
        Joint_16_Object_16_Material_16: THREE.MeshBasicMaterial
        Joint_16_Object_5_Material_5: THREE.MeshBasicMaterial
        Joint_18_Object_2_Material_2: THREE.MeshStandardMaterial
        Joint_19_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_1_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_20_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_3_Object_10_Material_10: THREE.MeshBasicMaterial
        Joint_3_Object_15_Material_15: THREE.MeshBasicMaterial
        Joint_3_Object_1_Material_1: THREE.MeshBasicMaterial
        Joint_4_Object_0_Material_0: THREE.MeshBasicMaterial
        Joint_4_Object_10_Material_10: THREE.MeshBasicMaterial
        Joint_4_Object_11_Material_11: THREE.MeshBasicMaterial
        Joint_4_Object_12_Material_12: THREE.MeshBasicMaterial
        Joint_4_Object_13_Material_13: THREE.MeshBasicMaterial
        Joint_4_Object_19_Material_19: THREE.MeshStandardMaterial
        Joint_4_Object_3_Material_3: THREE.MeshBasicMaterial
        Joint_6_Object_1_Material_1: THREE.MeshBasicMaterial
        ['Joint_1_Object_0_Material_0.001']: THREE.MeshBasicMaterial
        Material: THREE.MeshBasicMaterial
        particle: THREE.MeshBasicMaterial
    },
    animations: GLTFAction[]
}

export default function YoshiStory(props: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>(null)
    const {
        nodes,
        materials,
        animations
    } = useGLTF(`YS_Render-transformed.glb`) as unknown as GLTFResult
    const {actions} = useAnimations(animations, group)

    const music = new Audio("music/YoshiStory.mp3");
    music.loop = true;
    music.volume = 0.05;

    useEffect(() => {
        // This moves Randall
        actions["ArmatureAction"]?.play()
        music.play()
        return () => {
            music.pause()
        }
    }, [])


    return (
        <group ref={group} {...props} dispose={null}>
            <group name="model">
                <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.7}>
                    <primitive object={nodes.JOBJ_0}/>
                    <skinnedMesh name="Joint_10_Object_0_SINGLE" geometry={nodes.Joint_10_Object_0_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_10_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_1_SINGLE" geometry={nodes.Joint_10_Object_1_SINGLE.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_10_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_2_SINGLE" geometry={nodes.Joint_10_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_2_Material_2}
                                 skeleton={nodes.Joint_10_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_10_Object_3_SINGLE" geometry={nodes.Joint_10_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_10_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_0_SINGLE" geometry={nodes.Joint_11_Object_0_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_11_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_1_SINGLE" geometry={nodes.Joint_11_Object_1_SINGLE.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_11_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_2_SINGLE" geometry={nodes.Joint_11_Object_2_SINGLE.geometry}
                                 material={materials.Joint_11_Object_2_Material_2}
                                 skeleton={nodes.Joint_11_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_11_Object_3_SINGLE" geometry={nodes.Joint_11_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_11_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_0_SINGLE001"
                                 geometry={nodes.Joint_12_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_12_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_12_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_1_SINGLE001"
                                 geometry={nodes.Joint_12_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_12_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_2_SINGLE" geometry={nodes.Joint_12_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_12_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_3_SINGLE" geometry={nodes.Joint_12_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_12_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_13_Object_0_SINGLE001"
                                 geometry={nodes.Joint_13_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_12_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_13_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_13_Object_1_SINGLE001"
                                 geometry={nodes.Joint_13_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_13_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_13_Object_2_SINGLE" geometry={nodes.Joint_13_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_13_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_13_Object_3_SINGLE" geometry={nodes.Joint_13_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_13_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_14_Object_0_SINGLE001"
                                 geometry={nodes.Joint_14_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_14_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_14_Object_1_SINGLE001"
                                 geometry={nodes.Joint_14_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_14_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_14_Object_2_SINGLE" geometry={nodes.Joint_14_Object_2_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_14_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_14_Object_3_SINGLE" geometry={nodes.Joint_14_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_14_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_15_Object_0_SINGLE001"
                                 geometry={nodes.Joint_15_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_12_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_15_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_15_Object_1_SINGLE001"
                                 geometry={nodes.Joint_15_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_15_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_15_Object_2_SINGLE" geometry={nodes.Joint_15_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_15_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_15_Object_3_SINGLE" geometry={nodes.Joint_15_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_15_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_0_SINGLE001"
                                 geometry={nodes.Joint_16_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_1_SINGLE001"
                                 geometry={nodes.Joint_16_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_16_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_2_SINGLE001"
                                 geometry={nodes.Joint_16_Object_2_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_16_Object_2_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_17_Object_0_SINGLE001"
                                 geometry={nodes.Joint_17_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_17_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_17_Object_1_SINGLE001"
                                 geometry={nodes.Joint_17_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_17_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_17_Object_2_SINGLE" geometry={nodes.Joint_17_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_17_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_0_SINGLE001"
                                 geometry={nodes.Joint_18_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_1_SINGLE001"
                                 geometry={nodes.Joint_18_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_18_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_2_SINGLE001"
                                 geometry={nodes.Joint_18_Object_2_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_2_Material_2}
                                 skeleton={nodes.Joint_18_Object_2_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_3_SINGLE001"
                                 geometry={nodes.Joint_18_Object_3_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_18_Object_3_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_19_Object_0_SINGLE001"
                                 geometry={nodes.Joint_19_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_19_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_19_Object_1_SINGLE001"
                                 geometry={nodes.Joint_19_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_19_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_19_Object_2_SINGLE" geometry={nodes.Joint_19_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_2_Material_2}
                                 skeleton={nodes.Joint_19_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_19_Object_3_SINGLE" geometry={nodes.Joint_19_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_19_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_0_SINGLE002" geometry={nodes.Joint_1_Object_0_SINGLE002.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_1_Object_0_SINGLE002.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_1_SINGLE001" geometry={nodes.Joint_1_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_2_Material_2}
                                 skeleton={nodes.Joint_1_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_2_SINGLE" geometry={nodes.Joint_1_Object_2_SINGLE.geometry}
                                 material={materials.Joint_1_Object_2_Material_2}
                                 skeleton={nodes.Joint_1_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_3_SINGLE" geometry={nodes.Joint_1_Object_3_SINGLE.geometry}
                                 material={materials['Joint_1_Object_3_Material_3.001']}
                                 skeleton={nodes.Joint_1_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_3_SINGLE001" geometry={nodes.Joint_1_Object_3_SINGLE001.geometry}
                                 material={materials['Joint_1_Object_3_Material_3.001']}
                                 skeleton={nodes.Joint_1_Object_3_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_20_Object_0_SINGLE001"
                                 geometry={nodes.Joint_20_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_20_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_20_Object_1_SINGLE001"
                                 geometry={nodes.Joint_20_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_20_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_20_Object_2_SINGLE" geometry={nodes.Joint_20_Object_2_SINGLE.geometry}
                                 material={materials.Joint_20_Object_2_Material_2}
                                 skeleton={nodes.Joint_20_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_20_Object_3_SINGLE" geometry={nodes.Joint_20_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_20_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_21_Object_0_SINGLE" geometry={nodes.Joint_21_Object_0_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_21_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_21_Object_1_SINGLE" geometry={nodes.Joint_21_Object_1_SINGLE.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_21_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_21_Object_2_SINGLE" geometry={nodes.Joint_21_Object_2_SINGLE.geometry}
                                 material={materials.Joint_11_Object_2_Material_2}
                                 skeleton={nodes.Joint_21_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_21_Object_3_SINGLE" geometry={nodes.Joint_21_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_21_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_22_Object_0_SINGLE" geometry={nodes.Joint_22_Object_0_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_22_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_22_Object_1_SINGLE" geometry={nodes.Joint_22_Object_1_SINGLE.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_22_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_22_Object_2_SINGLE" geometry={nodes.Joint_22_Object_2_SINGLE.geometry}
                                 material={materials.Joint_11_Object_2_Material_2}
                                 skeleton={nodes.Joint_22_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_22_Object_3_SINGLE" geometry={nodes.Joint_22_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_22_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_23_Object_0_SINGLE" geometry={nodes.Joint_23_Object_0_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_23_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_23_Object_1_SINGLE" geometry={nodes.Joint_23_Object_1_SINGLE.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_23_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_23_Object_2_SINGLE" geometry={nodes.Joint_23_Object_2_SINGLE.geometry}
                                 material={materials.Joint_11_Object_2_Material_2}
                                 skeleton={nodes.Joint_23_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_23_Object_3_SINGLE" geometry={nodes.Joint_23_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_23_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_24_Object_0_SINGLE" geometry={nodes.Joint_24_Object_0_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_24_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_24_Object_1_SINGLE" geometry={nodes.Joint_24_Object_1_SINGLE.geometry}
                                 material={materials.Joint_24_Object_1_Material_1}
                                 skeleton={nodes.Joint_24_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_24_Object_2_SINGLE" geometry={nodes.Joint_24_Object_2_SINGLE.geometry}
                                 material={materials['Joint_12_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_24_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_24_Object_3_SINGLE" geometry={nodes.Joint_24_Object_3_SINGLE.geometry}
                                 material={materials.Joint_24_Object_3_Material_3}
                                 skeleton={nodes.Joint_24_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_2_Object_0_SINGLE001" geometry={nodes.Joint_2_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_2_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_2_Object_1_SINGLE001" geometry={nodes.Joint_2_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_2_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_2_Object_2_SINGLE" geometry={nodes.Joint_2_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_2_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_0_SINGLE001" geometry={nodes.Joint_3_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_1_SINGLE001" geometry={nodes.Joint_3_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_3_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_2_SINGLE001" geometry={nodes.Joint_3_Object_2_SINGLE001.geometry}
                                 material={materials.Joint_20_Object_2_Material_2}
                                 skeleton={nodes.Joint_3_Object_2_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_3_SINGLE001" geometry={nodes.Joint_3_Object_3_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_3_Object_3_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_0_SINGLE001" geometry={nodes.Joint_4_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_4_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_1_SINGLE001" geometry={nodes.Joint_4_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_4_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_2_SINGLE001" geometry={nodes.Joint_4_Object_2_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_4_Object_2_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_3_SINGLE001" geometry={nodes.Joint_4_Object_3_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_4_Object_3_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_5_Object_0_SINGLE" geometry={nodes.Joint_5_Object_0_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_5_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_5_Object_1_SINGLE" geometry={nodes.Joint_5_Object_1_SINGLE.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_5_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_5_Object_2_SINGLE" geometry={nodes.Joint_5_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_2_Material_2}
                                 skeleton={nodes.Joint_5_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_5_Object_3_SINGLE" geometry={nodes.Joint_5_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_5_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_6_Object_0_SINGLE001" geometry={nodes.Joint_6_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_6_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_6_Object_1_SINGLE001" geometry={nodes.Joint_6_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_6_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_6_Object_2_SINGLE" geometry={nodes.Joint_6_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_2_Material_2}
                                 skeleton={nodes.Joint_6_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_6_Object_3_SINGLE" geometry={nodes.Joint_6_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_6_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_0_SINGLE001" geometry={nodes.Joint_7_Object_0_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_7_Object_0_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_1_SINGLE001" geometry={nodes.Joint_7_Object_1_SINGLE001.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_7_Object_1_SINGLE001.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_2_SINGLE" geometry={nodes.Joint_7_Object_2_SINGLE.geometry}
                                 material={materials.Joint_11_Object_2_Material_2}
                                 skeleton={nodes.Joint_7_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_3_SINGLE" geometry={nodes.Joint_7_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_7_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_8_Object_0_SINGLE" geometry={nodes.Joint_8_Object_0_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_8_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_8_Object_1_SINGLE" geometry={nodes.Joint_8_Object_1_SINGLE.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_8_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_8_Object_2_SINGLE" geometry={nodes.Joint_8_Object_2_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_8_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_9_Object_0_SINGLE" geometry={nodes.Joint_9_Object_0_SINGLE.geometry}
                                 material={materials.Joint_10_Object_0_Material_0}
                                 skeleton={nodes.Joint_9_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_9_Object_1_SINGLE" geometry={nodes.Joint_9_Object_1_SINGLE.geometry}
                                 material={materials.Joint_10_Object_1_Material_1}
                                 skeleton={nodes.Joint_9_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_9_Object_2_SINGLE" geometry={nodes.Joint_9_Object_2_SINGLE.geometry}
                                 material={materials.Joint_9_Object_2_Material_2}
                                 skeleton={nodes.Joint_9_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_9_Object_3_SINGLE" geometry={nodes.Joint_9_Object_3_SINGLE.geometry}
                                 material={materials.Joint_10_Object_3_Material_3}
                                 skeleton={nodes.Joint_9_Object_3_SINGLE.skeleton}/>
                </group>
                <group name="model_skeleton" scale={0.7}>
                    <primitive object={nodes.JOBJ_0_1}/>
                    <skinnedMesh name="Joint_12_Object_0_SINGLE" geometry={nodes.Joint_12_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_12_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_12_Object_1_SINGLE" geometry={nodes.Joint_12_Object_1_SINGLE.geometry}
                                 material={materials.Joint_12_Object_1_Material_1}
                                 skeleton={nodes.Joint_12_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_13_Object_0_SINGLE" geometry={nodes.Joint_13_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_13_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_13_Object_1_SINGLE" geometry={nodes.Joint_13_Object_1_SINGLE.geometry}
                                 material={materials.Joint_13_Object_1_Material_1}
                                 skeleton={nodes.Joint_13_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_14_Object_0_SINGLE" geometry={nodes.Joint_14_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_14_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_14_Object_1_SINGLE" geometry={nodes.Joint_14_Object_1_SINGLE.geometry}
                                 material={materials.Joint_14_Object_1_Material_1}
                                 skeleton={nodes.Joint_14_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_15_Object_0_SINGLE" geometry={nodes.Joint_15_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_15_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_15_Object_1_SINGLE" geometry={nodes.Joint_15_Object_1_SINGLE.geometry}
                                 material={materials.Joint_15_Object_1_Material_1}
                                 skeleton={nodes.Joint_15_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_0_SINGLE" geometry={nodes.Joint_16_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_10_SINGLE" geometry={nodes.Joint_16_Object_10_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_10_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_11_SINGLE" geometry={nodes.Joint_16_Object_11_SINGLE.geometry}
                                 material={materials.Joint_16_Object_11_Material_11}
                                 skeleton={nodes.Joint_16_Object_11_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_12_SINGLE" geometry={nodes.Joint_16_Object_12_SINGLE.geometry}
                                 material={materials.Joint_20_Object_2_Material_2}
                                 skeleton={nodes.Joint_16_Object_12_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_13_SINGLE" geometry={nodes.Joint_16_Object_13_SINGLE.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_16_Object_13_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_14_SINGLE" geometry={nodes.Joint_16_Object_14_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_14_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_15_SINGLE" geometry={nodes.Joint_16_Object_15_SINGLE.geometry}
                                 material={materials.Joint_16_Object_15_Material_15}
                                 skeleton={nodes.Joint_16_Object_15_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_16_SINGLE" geometry={nodes.Joint_16_Object_16_SINGLE.geometry}
                                 material={materials.Joint_16_Object_16_Material_16}
                                 skeleton={nodes.Joint_16_Object_16_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_1_SINGLE" geometry={nodes.Joint_16_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_2_SINGLE" geometry={nodes.Joint_16_Object_2_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_3_SINGLE" geometry={nodes.Joint_16_Object_3_SINGLE.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_16_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_4_SINGLE" geometry={nodes.Joint_16_Object_4_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_5_SINGLE" geometry={nodes.Joint_16_Object_5_SINGLE.geometry}
                                 material={materials.Joint_16_Object_5_Material_5}
                                 skeleton={nodes.Joint_16_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_6_SINGLE" geometry={nodes.Joint_16_Object_6_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_6_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_7_SINGLE" geometry={nodes.Joint_16_Object_7_SINGLE.geometry}
                                 material={materials.Joint_16_Object_5_Material_5}
                                 skeleton={nodes.Joint_16_Object_7_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_8_SINGLE" geometry={nodes.Joint_16_Object_8_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_16_Object_8_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_16_Object_9_SINGLE" geometry={nodes.Joint_16_Object_9_SINGLE.geometry}
                                 material={materials.Joint_16_Object_5_Material_5}
                                 skeleton={nodes.Joint_16_Object_9_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_17_Object_0_SINGLE" geometry={nodes.Joint_17_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_17_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_17_Object_1_SINGLE" geometry={nodes.Joint_17_Object_1_SINGLE.geometry}
                                 material={materials.Joint_15_Object_1_Material_1}
                                 skeleton={nodes.Joint_17_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_0_SINGLE" geometry={nodes.Joint_18_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_10_SINGLE" geometry={nodes.Joint_18_Object_10_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_10_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_11_SINGLE" geometry={nodes.Joint_18_Object_11_SINGLE.geometry}
                                 material={materials.Joint_16_Object_11_Material_11}
                                 skeleton={nodes.Joint_18_Object_11_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_12_SINGLE" geometry={nodes.Joint_18_Object_12_SINGLE.geometry}
                                 material={materials.Joint_20_Object_2_Material_2}
                                 skeleton={nodes.Joint_18_Object_12_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_13_SINGLE" geometry={nodes.Joint_18_Object_13_SINGLE.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_18_Object_13_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_14_SINGLE" geometry={nodes.Joint_18_Object_14_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_14_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_15_SINGLE" geometry={nodes.Joint_18_Object_15_SINGLE.geometry}
                                 material={materials.Joint_16_Object_15_Material_15}
                                 skeleton={nodes.Joint_18_Object_15_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_16_SINGLE" geometry={nodes.Joint_18_Object_16_SINGLE.geometry}
                                 material={materials.Joint_16_Object_16_Material_16}
                                 skeleton={nodes.Joint_18_Object_16_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_1_SINGLE" geometry={nodes.Joint_18_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_2_SINGLE" geometry={nodes.Joint_18_Object_2_SINGLE.geometry}
                                 material={materials.Joint_18_Object_2_Material_2}
                                 skeleton={nodes.Joint_18_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_3_SINGLE" geometry={nodes.Joint_18_Object_3_SINGLE.geometry}
                                 material={materials.Joint_11_Object_1_Material_1}
                                 skeleton={nodes.Joint_18_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_4_SINGLE" geometry={nodes.Joint_18_Object_4_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_5_SINGLE" geometry={nodes.Joint_18_Object_5_SINGLE.geometry}
                                 material={materials.Joint_16_Object_5_Material_5}
                                 skeleton={nodes.Joint_18_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_6_SINGLE" geometry={nodes.Joint_18_Object_6_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_6_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_7_SINGLE" geometry={nodes.Joint_18_Object_7_SINGLE.geometry}
                                 material={materials.Joint_16_Object_5_Material_5}
                                 skeleton={nodes.Joint_18_Object_7_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_8_SINGLE" geometry={nodes.Joint_18_Object_8_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_18_Object_8_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_18_Object_9_SINGLE" geometry={nodes.Joint_18_Object_9_SINGLE.geometry}
                                 material={materials.Joint_16_Object_5_Material_5}
                                 skeleton={nodes.Joint_18_Object_9_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_19_Object_0_SINGLE" geometry={nodes.Joint_19_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_19_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_19_Object_1_SINGLE" geometry={nodes.Joint_19_Object_1_SINGLE.geometry}
                                 material={materials.Joint_19_Object_1_Material_1}
                                 skeleton={nodes.Joint_19_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_0_SINGLE" geometry={nodes.Joint_1_Object_0_SINGLE.geometry}
                                 material={materials.Joint_1_Object_0_Material_0}
                                 skeleton={nodes.Joint_1_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_1_Object_1_SINGLE" geometry={nodes.Joint_1_Object_1_SINGLE.geometry}
                                 material={materials.Joint_1_Object_0_Material_0}
                                 skeleton={nodes.Joint_1_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_20_Object_0_SINGLE" geometry={nodes.Joint_20_Object_0_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_20_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_20_Object_1_SINGLE" geometry={nodes.Joint_20_Object_1_SINGLE.geometry}
                                 material={materials.Joint_20_Object_1_Material_1}
                                 skeleton={nodes.Joint_20_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_2_Object_0_SINGLE" geometry={nodes.Joint_2_Object_0_SINGLE.geometry}
                                 material={materials.Joint_1_Object_0_Material_0}
                                 skeleton={nodes.Joint_2_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_2_Object_1_SINGLE" geometry={nodes.Joint_2_Object_1_SINGLE.geometry}
                                 material={materials.Joint_1_Object_0_Material_0}
                                 skeleton={nodes.Joint_2_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_0_SINGLE" geometry={nodes.Joint_3_Object_0_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_10_SINGLE" geometry={nodes.Joint_3_Object_10_SINGLE.geometry}
                                 material={materials.Joint_3_Object_10_Material_10}
                                 skeleton={nodes.Joint_3_Object_10_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_11_SINGLE" geometry={nodes.Joint_3_Object_11_SINGLE.geometry}
                                 material={materials.Joint_16_Object_15_Material_15}
                                 skeleton={nodes.Joint_3_Object_11_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_12_SINGLE" geometry={nodes.Joint_3_Object_12_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_12_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_13_SINGLE" geometry={nodes.Joint_3_Object_13_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_13_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_14_SINGLE" geometry={nodes.Joint_3_Object_14_SINGLE.geometry}
                                 material={materials.Joint_3_Object_10_Material_10}
                                 skeleton={nodes.Joint_3_Object_14_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_15_SINGLE" geometry={nodes.Joint_3_Object_15_SINGLE.geometry}
                                 material={materials.Joint_3_Object_15_Material_15}
                                 skeleton={nodes.Joint_3_Object_15_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_16_SINGLE" geometry={nodes.Joint_3_Object_16_SINGLE.geometry}
                                 material={materials.Joint_16_Object_15_Material_15}
                                 skeleton={nodes.Joint_3_Object_16_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_17_SINGLE" geometry={nodes.Joint_3_Object_17_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_17_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_18_SINGLE" geometry={nodes.Joint_3_Object_18_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_18_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_19_SINGLE" geometry={nodes.Joint_3_Object_19_SINGLE.geometry}
                                 material={materials.Joint_3_Object_10_Material_10}
                                 skeleton={nodes.Joint_3_Object_19_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_1_SINGLE" geometry={nodes.Joint_3_Object_1_SINGLE.geometry}
                                 material={materials.Joint_3_Object_1_Material_1}
                                 skeleton={nodes.Joint_3_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_20_SINGLE" geometry={nodes.Joint_3_Object_20_SINGLE.geometry}
                                 material={materials.Joint_3_Object_15_Material_15}
                                 skeleton={nodes.Joint_3_Object_20_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_21_SINGLE" geometry={nodes.Joint_3_Object_21_SINGLE.geometry}
                                 material={materials.Joint_16_Object_15_Material_15}
                                 skeleton={nodes.Joint_3_Object_21_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_22_SINGLE" geometry={nodes.Joint_3_Object_22_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_22_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_23_SINGLE" geometry={nodes.Joint_3_Object_23_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_23_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_24_SINGLE" geometry={nodes.Joint_3_Object_24_SINGLE.geometry}
                                 material={materials.Joint_3_Object_10_Material_10}
                                 skeleton={nodes.Joint_3_Object_24_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_25_SINGLE" geometry={nodes.Joint_3_Object_25_SINGLE.geometry}
                                 material={materials.Joint_16_Object_15_Material_15}
                                 skeleton={nodes.Joint_3_Object_25_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_2_SINGLE" geometry={nodes.Joint_3_Object_2_SINGLE.geometry}
                                 material={materials.Joint_16_Object_11_Material_11}
                                 skeleton={nodes.Joint_3_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_3_SINGLE" geometry={nodes.Joint_3_Object_3_SINGLE.geometry}
                                 material={materials.Joint_11_Object_2_Material_2}
                                 skeleton={nodes.Joint_3_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_4_SINGLE" geometry={nodes.Joint_3_Object_4_SINGLE.geometry}
                                 material={materials.Joint_16_Object_11_Material_11}
                                 skeleton={nodes.Joint_3_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_5_SINGLE" geometry={nodes.Joint_3_Object_5_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_6_SINGLE" geometry={nodes.Joint_3_Object_6_SINGLE.geometry}
                                 material={materials['Joint_14_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_3_Object_6_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_7_SINGLE" geometry={nodes.Joint_3_Object_7_SINGLE.geometry}
                                 material={materials.Joint_11_Object_2_Material_2}
                                 skeleton={nodes.Joint_3_Object_7_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_8_SINGLE" geometry={nodes.Joint_3_Object_8_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_8_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_3_Object_9_SINGLE" geometry={nodes.Joint_3_Object_9_SINGLE.geometry}
                                 material={materials.Joint_11_Object_0_Material_0}
                                 skeleton={nodes.Joint_3_Object_9_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_0_SINGLE" geometry={nodes.Joint_4_Object_0_SINGLE.geometry}
                                 material={materials.Joint_4_Object_0_Material_0}
                                 skeleton={nodes.Joint_4_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_10_SINGLE" geometry={nodes.Joint_4_Object_10_SINGLE.geometry}
                                 material={materials.Joint_4_Object_10_Material_10}
                                 skeleton={nodes.Joint_4_Object_10_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_11_SINGLE" geometry={nodes.Joint_4_Object_11_SINGLE.geometry}
                                 material={materials.Joint_4_Object_11_Material_11}
                                 skeleton={nodes.Joint_4_Object_11_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_12_SINGLE" geometry={nodes.Joint_4_Object_12_SINGLE.geometry}
                                 material={materials.Joint_4_Object_12_Material_12}
                                 skeleton={nodes.Joint_4_Object_12_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_13_SINGLE" geometry={nodes.Joint_4_Object_13_SINGLE.geometry}
                                 material={materials.Joint_4_Object_13_Material_13}
                                 skeleton={nodes.Joint_4_Object_13_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_14_SINGLE" geometry={nodes.Joint_4_Object_14_SINGLE.geometry}
                                 material={materials.Joint_4_Object_11_Material_11}
                                 skeleton={nodes.Joint_4_Object_14_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_15_SINGLE" geometry={nodes.Joint_4_Object_15_SINGLE.geometry}
                                 material={materials.Joint_4_Object_12_Material_12}
                                 skeleton={nodes.Joint_4_Object_15_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_16_SINGLE" geometry={nodes.Joint_4_Object_16_SINGLE.geometry}
                                 material={materials.Joint_4_Object_11_Material_11}
                                 skeleton={nodes.Joint_4_Object_16_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_17_SINGLE" geometry={nodes.Joint_4_Object_17_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_4_Object_17_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_18_SINGLE" geometry={nodes.Joint_4_Object_18_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_4_Object_18_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_19_SINGLE" geometry={nodes.Joint_4_Object_19_SINGLE.geometry}
                                 material={materials.Joint_4_Object_19_Material_19}
                                 skeleton={nodes.Joint_4_Object_19_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_1_SINGLE" geometry={nodes.Joint_4_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_4_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_2_SINGLE" geometry={nodes.Joint_4_Object_2_SINGLE.geometry}
                                 material={materials.Joint_12_Object_0_Material_0}
                                 skeleton={nodes.Joint_4_Object_2_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_3_SINGLE" geometry={nodes.Joint_4_Object_3_SINGLE.geometry}
                                 material={materials.Joint_4_Object_3_Material_3}
                                 skeleton={nodes.Joint_4_Object_3_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_4_SINGLE" geometry={nodes.Joint_4_Object_4_SINGLE.geometry}
                                 material={materials.Joint_4_Object_3_Material_3}
                                 skeleton={nodes.Joint_4_Object_4_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_5_SINGLE" geometry={nodes.Joint_4_Object_5_SINGLE.geometry}
                                 material={materials.Joint_4_Object_12_Material_12}
                                 skeleton={nodes.Joint_4_Object_5_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_6_SINGLE" geometry={nodes.Joint_4_Object_6_SINGLE.geometry}
                                 material={materials.Joint_3_Object_1_Material_1}
                                 skeleton={nodes.Joint_4_Object_6_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_7_SINGLE" geometry={nodes.Joint_4_Object_7_SINGLE.geometry}
                                 material={materials.Joint_4_Object_11_Material_11}
                                 skeleton={nodes.Joint_4_Object_7_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_8_SINGLE" geometry={nodes.Joint_4_Object_8_SINGLE.geometry}
                                 material={materials.Joint_4_Object_12_Material_12}
                                 skeleton={nodes.Joint_4_Object_8_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_4_Object_9_SINGLE" geometry={nodes.Joint_4_Object_9_SINGLE.geometry}
                                 material={materials.Joint_4_Object_10_Material_10}
                                 skeleton={nodes.Joint_4_Object_9_SINGLE.skeleton}/>
                </group>
                <group name="pak_skeleton" scale={0.7}>
                    <primitive object={nodes.JOBJ_0_2}/>
                    <skinnedMesh name="Joint_6_Object_0_SINGLE" geometry={nodes.Joint_6_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_6_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_6_Object_1_SINGLE" geometry={nodes.Joint_6_Object_1_SINGLE.geometry}
                                 material={materials.Joint_6_Object_1_Material_1}
                                 skeleton={nodes.Joint_6_Object_1_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_0_SINGLE" geometry={nodes.Joint_7_Object_0_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_7_Object_0_SINGLE.skeleton}/>
                    <skinnedMesh name="Joint_7_Object_1_SINGLE" geometry={nodes.Joint_7_Object_1_SINGLE.geometry}
                                 material={materials.Joint_16_Object_0_Material_0}
                                 skeleton={nodes.Joint_7_Object_1_SINGLE.skeleton}/>
                </group>
                <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.7}>
                    <primitive object={nodes.JOBJ_0_3}/>
                    <skinnedMesh name="Joint_1_Object_0_SINGLE001" geometry={nodes.Joint_1_Object_0_SINGLE001.geometry}
                                 material={materials['Joint_1_Object_0_Material_0.001']}
                                 skeleton={nodes.Joint_1_Object_0_SINGLE001.skeleton}/>
                </group>
                <pointLight name="Point" intensity={25000} decay={2} color="#b6b6b6" position={[-500, 800, 700]}
                            rotation={[-Math.PI / 2, 0, 0]}/>
                {/*<lineSegments name="Path" geometry={nodes.Path.geometry} material={nodes.Path.material}*/}
                {/*              position={[0, -28.69, 0]} scale={0.7}/>*/}
                <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material}
                      position={[-63.84, -49.31, 0]}/>
                <mesh name="particle" geometry={nodes.particle.geometry} material={materials.particle} scale={0.7}/>
            </group>
        </group>
    )
}

useGLTF.preload('YS_Render-transformed.glb')
